import assert from "node:assert/strict";
import {assessBalancingReport, bpcSettingsMatchRequest, extractBpcBalancingSettings, applySettingsObservation, runBalancingVerification, summarizeBalancingVerification, createReadLimiter, type BalancingVerificationJob, type StringVerification} from "./balancingVerification";
const request = {mode: "avg" as const, chargingDeadband: 5, dischargingDeadband: 10};
const row = (): StringVerification => ({array: 1, string: 2, expectedBpcs: 2, acceptedAt: 1000, status: "pending", detail: ""});
const report = (targets = [3266, 3267], timestamp = 2000) => ({timeStamp: timestamp, batteryPackReportList: targets.map((v, i) => ({batteryPackIndex: i + 1, timeStamp: timestamp, batteryPackData: {batteryPackBalancingConfiguration: {balancingMode: "BALANCE_TO_PROVIDED", chargeDeadband: 5, dischargeDeadband: 10, providedVoltageTarget: v}}}))});
assert.equal(assessBalancingReport(report(), request, row(), 3000).status, "matched");
assert.equal(assessBalancingReport(report([3266]), request, row(), 3000).status, "unavailable");
assert.equal(assessBalancingReport(report([3266,3267], 999), request, row(), 3000).status, "unavailable");
assert.equal(assessBalancingReport(report(), request, row(), 33_000).status, "unavailable");
const stalePack = report(); stalePack.batteryPackReportList[1].timeStamp = 999;
assert.equal(assessBalancingReport(stalePack, request, row(), 3000).status, "unavailable");
const duplicate = report(); duplicate.batteryPackReportList[1].batteryPackIndex = 1;
assert.equal(assessBalancingReport(duplicate, request, row(), 3000).status, "unavailable");
assert.equal(bpcSettingsMatchRequest(extractBpcBalancingSettings(report()), {...request, mode: "provided", providedMv: 3266}), false);
assert.equal(bpcSettingsMatchRequest(extractBpcBalancingSettings(report([3266,3270])), request), false);
assert.equal(bpcSettingsMatchRequest(extractBpcBalancingSettings(report()), {...request, chargingDeadband: 1}), false);
const r = row();
applySettingsObservation(r, {status: "mismatch", detail: "Off"}, 2000);
assert.equal(r.status, "pending");
applySettingsObservation(r, {status: "mismatch", detail: "Off"}, 181000);
assert.equal(r.status, "mismatch", "Never-matched is not changed");
const matched = row();
applySettingsObservation(matched, {status: "matched", sourceAt: 2000, detail: "5/10"}, 2000);
applySettingsObservation(matched, {status: "mismatch", detail: "Off"}, 67000);
assert.equal(matched.status, "pending", "Allow transient persistence readback to recover");
applySettingsObservation(matched, {status: "mismatch", detail: "Off"}, 97000);
assert.equal(matched.status, "changed");
const job: BalancingVerificationJob = {id: "fixture", status: "pending", createdAt: 1000, updatedAt: 1000, request, strings: [row(), {...row(), string: 3}, {...row(), string: 4, status: "not-accepted"}]};
let clock = 1000;
let reads = 0;
await runBalancingVerification(job, async target => {reads++; return target.string === 2 && clock >= 3000 ? {status: "matched", sourceAt: clock, detail: "5/10"} : {status: "mismatch", sourceAt: clock, detail: "Off"};},
  {now: () => clock, wait: async ms => {clock += ms;}, timing: {settleMs: 5000, persistenceMs: 6500, recoveryMs: 3000, intervalMs: 1000}});
assert.equal(job.status, "complete"); assert.equal(job.strings[0].status, "persisted"); assert.equal(job.strings[1].status, "mismatch");
assert.deepEqual(summarizeBalancingVerification(job), {total: 3, verified: 1, persisted: 1, pending: 0, unresolved: 2});
assert(reads < 18, "Matched strings are not repeatedly read before persistence is due");
const cached = row();
applySettingsObservation(cached, {status: "matched", sourceAt: 2000, detail: "5/10"}, 2000);
applySettingsObservation(cached, {status: "matched", sourceAt: 2000, detail: "5/10"}, 97000);
assert.equal(cached.status, "unavailable", "Same sample cannot establish persistence");
const limit = createReadLimiter(4); let active = 0; let peak = 0;
await Promise.all(Array.from({length: 24}, () => limit(async () => {peak = Math.max(peak, ++active); await new Promise(r => setTimeout(r, 1)); active--;})));
assert.equal(peak, 4);
console.log("Balancing verification freshness, partial results, timing, drift and read limiting passed");
