import assert from 'node:assert/strict';
import {buildNotificationReview} from './notificationReview';
const at='2026-09-28T17:00:00Z';
const make=(bpc:number,cell:number,array=1,string=2,block=1)=>({code:'1001',severity:'alarm',recommendedActions:['Shared guidance'],affected:[{blockIndex:block,arrayIndex:array,stringIndex:string,batteryPackIndex:bpc,cellGroupIndex:cell,timestamp:'1790614800000',label:`Array ${array} / String ${string} / BPC ${bpc} / CG ${cell}`}],evidence:{currentA:cell}});
const inputs=[make(3,1),make(3,2),make(3,2),make(4,5),make(3,1,2),make(3,1,1,3),make(3,1,1,2,2)];
const before=JSON.stringify(inputs);
const review=buildNotificationReview(inputs,at),group=review.groups[0];
assert.equal(JSON.stringify(inputs),before);
assert.equal(group.targetCount,6,'duplicate cells deduplicated, distinct cells/strings/arrays/blocks preserved');
assert.equal(group.tableRows?.length,4);
assert.equal(group.tableRows?.flatMap(row=>row.memberIds).length,group.targetCount);
assert.equal(new Set(group.tableRows?.flatMap(row=>row.memberIds)).size,group.targetCount);
const row=group.tableRows!.find(row=>row.label==='Array 1 / String 2')!;
assert.deepEqual(row.scope,['BPC 3 · Cell groups 1, 2','BPC 4 · Cell groups 5']);
assert.equal(row.observations.length,3,'different measurements retain their scope');
assert(row.observations.find(o=>o.evidence[0].value==='5')?.scope.includes('BPC 4 · Cell groups 5'));
assert(row.observations.every(o=>o.times[0]===new Date(1790614800000).toISOString() && !o.missingTime));
assert.deepEqual(group.commonGuidance,['Shared guidance']);
assert(row.observations.every(o=>!o.guidance.length));
assert.equal(review.totals.alarm,6,'row consolidation is not alarm suppression');
const unmatched=buildNotificationReview([{code:'1001',affected:[{arrayIndex:1,batteryPackIndex:1,cellGroupIndex:1},{arrayIndex:1,batteryPackIndex:1,cellGroupIndex:2}]}],at);
assert.equal(unmatched.groups[0].tableRows?.length,2,'without a string identity do not infer common parent');
const other=buildNotificationReview([{code:'X',affected:[{arrayIndex:1,pcsIndex:1},{arrayIndex:1,pcsIndex:2}]},{code:'Y',affected:[{arrayIndex:1,energySegmentIndex:1,hvacUnit:1},{arrayIndex:1,energySegmentIndex:1,hvacUnit:2}]}],at);
assert(other.groups.every(g=>g.tableRows?.length===2));
const times=buildNotificationReview([{code:'1001',affected:[{arrayIndex:1,stringIndex:1,batteryPackIndex:1,cellGroupIndex:1,timestamp:at},{arrayIndex:1,stringIndex:1,batteryPackIndex:1,cellGroupIndex:2,timestamp:'invalid'}]}],at);
assert.equal(times.groups[0].tableRows?.[0].observations[0].missingTime,true);
assert.deepEqual(times.groups[0].tableRows?.[0].observations[0].times,[new Date(at).toISOString()]);
console.log('Notification table: scope consolidation, identity, count parity, measurements and timestamps passed');
