import assert from 'node:assert/strict';
import {buildNotificationReview} from './notificationReview';
const at='2026-09-28T17:00:00Z';
const row={arrayNumber:1,stringNumber:2,measuredVoltageVdc:1400,minCellVoltageMv:3300,maxCellVoltageMv:3400,
  avgCellTempC:24,minCellTempC:20,maxCellTempC:28,currentA:0,powerKw:0,sourceTimestampUtc:at,metricSource:'canonical-test'};
const issues=[1,2].map(cell=>({code:'2003',affected:[{blockIndex:1,arrayIndex:1,stringIndex:2,batteryPackIndex:4,cellGroupIndex:cell}]}));
const make=(strings:unknown[]=[row],code='2003',blockIndex:number|null=1)=>buildNotificationReview(issues.map(i=>({...i,code})),at,{strings,blockIndex});
const metrics=(strings:unknown[]=[row],code='2003',blockIndex:number|null=1)=>make(strings,code,blockIndex).groups[0].tableRows![0].metrics!;
assert.deepEqual(metrics().fields.map(f=>f.value),[1400,3300,3400,100]);
assert.equal(metrics().scope,'String context');assert.equal(metrics().quality,'available');
assert.deepEqual(make().totals,buildNotificationReview(issues,at).totals);
assert.equal(make().groups[0].tableRows!.length,1);
assert.equal(metrics([{...row,arrayNumber:2}]).quality,'unavailable');
assert.equal(metrics([row],'2003',2).quality,'unavailable');
assert.equal(metrics([row],'2003',null).quality,'unavailable');
assert.equal(metrics([row,row]).quality,'unavailable');
assert.equal(metrics([{...row,sourceTimestampUtc:undefined}]).quality,'time unknown');
assert.equal(metrics([{...row,sourceTimestampUtc:'2026-09-28T16:59:00Z'}]).quality,'stale');
assert.equal(metrics([{...row,sourceTimestampUtc:'2026-09-28T17:01:00Z'}]).quality,'time unknown');
for(const flag of ['stale','stalePreserved','staleData']) assert.equal(metrics([{...row,[flag]:true}]).quality,'stale');
assert.equal(metrics([{...row,communicating:false}]).quality,'stale');
assert.equal(metrics([{...row,badReport:true}]).quality,'unavailable');
assert.equal(metrics([{...row,measuredVoltageVdc:null,stackVoltageVdc:1500}]).fields[0].value,null,'no bus/calculated substitute for measured string voltage');
assert.deepEqual(metrics([{...row,minCellVoltageMv:3500}]).fields.slice(1).map(f=>f.value),[null,null,null]);
assert.deepEqual(metrics([row],'2010').fields.map(f=>f.value),[24,20,28,8]);
assert.deepEqual(metrics([row],'2019').fields.map(f=>f.value),[0,0,1400]);
for(const code of ['1003','2008','3008']) assert.deepEqual(metrics([row],code).fields.map(f=>f.value),[1400,3300,3400,100]);
for(const code of ['9999','2013','2017','2021']) assert.equal(metrics([row],code),undefined,'no guessing enclosure/ground measurements');
assert.equal(make().groups[0].targets[0].observations[0].evidence.length,0,'event evidence not rewritten');
assert.deepEqual(metrics([{...row,busVoltageVdc:1390}],'STR-CON-MISMATCH').fields.map(f=>f.value),[1400,1390,10]);
assert.deepEqual(metrics([{...row,minCellVoltageMv:NaN,maxCellVoltageMv:Infinity}]).fields.slice(1).map(f=>f.value),[null,null,null]);
assert.equal(buildNotificationReview(issues,at,{strings:[row],blockIndex:1,stale:true}).groups[0].tableRows![0].metrics!.quality,'stale');
console.log('Notification metric context tests passed');
