import { useEffect, useRef, useState } from 'react';
import type { WorkspaceRole } from './types';

export interface WorkspacePreviewData { snapshot: any; siteOperations: any; projection: any; loading: boolean; error: string | null; loadedAt: string | null; refresh(): void }
const inFlight = new Map<string, Promise<any>>();
function readProjection(endpoint: string): Promise<any> { const existing = inFlight.get(endpoint); if (existing) return existing; const request = fetch(endpoint).then((response) => { if (!response.ok) throw new Error(`${endpoint}: HTTP ${response.status}`); return response.json(); }).finally(() => inFlight.delete(endpoint)); inFlight.set(endpoint, request); return request; }

function adapt(envelope: any, role: WorkspaceRole) {
  const data = envelope?.data ?? {}; const base = { cycleId: envelope?.cycleId, liveStatus: { state: data?.site?.connectionState ?? data?.acquisitionHealth?.state ?? (envelope?.stale ? 'CACHED' : 'LIVE'), source: envelope?.sourceMode, stale: envelope?.stale, cacheUsed: envelope?.retainedLastKnownGood, ageMs: data?.telemetryTrust?.ageMs, lastUpdated: data?.telemetryTrust?.lastUpdated }, siteIdentity: data?.site ?? data?.activeProfile ?? null };
  if (role === 'operator') { const strings = (data.arrays ?? []).map((row: any) => ({ arrayIndex: row.arrayIndex, warningCount: row.warnings, alarmCount: row.alarms, communicating: row.offlineStrings ? false : true, stale: row.staleStrings > 0 })); const snapshot = { ...base, normalized: { strings, correctiveActions: data.prioritizedIssues ?? [] }, rollups: { bessFleetSummary: { systemSocPct: data.siteMetrics?.soc, measuredPowerKw: data.siteMetrics?.power, availableStoredKWh: data.siteMetrics?.availableCapacity }, arraySummary: data.arrays ?? [], featherSummary: data.environmentalRisk ?? {}, sourceHealthSummary: data.telemetryTrust ?? {} } }; return { snapshot, siteOperations: { site: data.site, arraySummary: data.arrays, activeIssueGroups: data.prioritizedIssues, featherSummary: data.environmentalRisk, bessFleetSummary: snapshot.rollups.bessFleetSummary }, projection: envelope }; }
  if (role === 'technician') { const strings = (data.strings ?? []).map((row: any) => ({ ...row, canonicalKey: row.canonicalIdentity, arrayNumber: row.arrayIndex, stringNumber: row.stringIndex, energySegmentNumber: row.energySegment, maxCellTemperature: row.maxTemperature, minCellTemperature: row.minTemperature, cellTemperatureDelta: row.temperatureDelta, avgCellVoltageMv: row.measuredVoltage, cellVoltageDelta: row.voltageDelta, socPct: row.soc, currentA: row.current, powerKw: row.power, communicating: !String(row.connectionState ?? '').toLowerCase().includes('offline') })); const snapshot = { ...base, normalized: { strings, correctiveActions: data.correctiveActions ?? [], sensors: [] }, rollups: { featherSummary: data.hvacFeather ?? {}, sensorsSummary: data.sensors?.summary ?? {} } }; return { snapshot, siteOperations: { featherSummary: data.hvacFeather, humidityTemperatureSensors: [], activeIssueGroups: data.activeFaults }, projection: envelope }; }
  return { snapshot: { ...base, graphVersion: data.graph?.graphFingerprint, authority: data.brokerAuthority, rollups: { sourceHealth: Object.values(data.providerHealth ?? {}), sourceHealthSummary: data.telemetryRuntime } }, siteOperations: data, projection: envelope };
}

export function useWorkspacePreviewData(role: WorkspaceRole): WorkspacePreviewData {
  const enabled = role !== 'legacy'; const [state, setState] = useState<Omit<WorkspacePreviewData, 'refresh'>>({ snapshot: null, siteOperations: null, projection: null, loading: false, error: null, loadedAt: null }); const requestRef = useRef(0); const [nonce, setNonce] = useState(0);
  useEffect(() => { if (!enabled) return; const requestId = ++requestRef.current; let active = true; const endpoint = `/api/local/workspaces/${role}`; setState((value) => ({ ...value, loading: true, error: null })); readProjection(endpoint).then((envelope) => { if (active && requestRef.current === requestId) setState({ ...adapt(envelope, role), loading: false, error: null, loadedAt: new Date().toISOString() }); }).catch((error) => { if (active && requestRef.current === requestId) setState((value) => ({ ...value, loading: false, error: error instanceof Error ? error.message : String(error) })); }); return () => { active = false; }; }, [enabled, role, nonce]);
  return { ...state, refresh: () => setNonce((value) => value + 1) };
}
