import React from 'react';
import { AlertTriangle, CheckCircle2, CircleHelp, LockKeyhole, WifiOff } from 'lucide-react';
import type { DataState } from './types';

export const tone = { good: 'border-emerald-500/35 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300', warning: 'border-amber-500/40 bg-amber-500/10 text-amber-700 dark:text-amber-300', danger: 'border-rose-500/40 bg-rose-500/10 text-rose-700 dark:text-rose-300', info: 'border-sky-500/35 bg-sky-500/10 text-sky-700 dark:text-sky-300', neutral: 'border-slate-300 bg-white/70 text-slate-700 dark:border-slate-700 dark:bg-slate-900/70 dark:text-slate-300' } as const;
export function Panel({ title, eyebrow, action, children, className = '' }: { title: string; eyebrow?: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-slate-300/80 bg-white/90 shadow-sm dark:border-slate-700 dark:bg-slate-900/90 ${className}`}><header className="flex min-h-14 items-center justify-between gap-3 border-b border-slate-200 px-4 py-3 dark:border-slate-800"><div>{eyebrow && <p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">{eyebrow}</p>}<h2 className="text-sm font-black tracking-tight text-slate-900 dark:text-slate-100">{title}</h2></div>{action}</header><div className="p-4">{children}</div></section>; }
export function Metric({ label, value, detail, state = 'neutral' }: { label: string; value: React.ReactNode; detail?: string; state?: keyof typeof tone }) { return <div className={`min-h-24 rounded-lg border p-3 ${tone[state]}`}><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] opacity-75">{label}</p><div className="mt-2 text-2xl font-black tabular-nums">{value}</div>{detail && <p className="mt-1 text-xs opacity-80">{detail}</p>}</div>; }
export function StatusPill({ children, state = 'neutral' }: { children: React.ReactNode; state?: keyof typeof tone }) { return <span className={`inline-flex items-center rounded-full border px-2 py-1 font-mono text-[10px] font-black uppercase tracking-wider ${tone[state]}`}>{children}</span>; }
export function DataStateBanner({ state, message }: { state: DataState; message?: string }) { const config = state === 'live' ? { icon: CheckCircle2, label: 'Live operational data', style: tone.good } : state === 'stale' ? { icon: AlertTriangle, label: 'Stale — last known data', style: tone.warning } : state === 'offline' ? { icon: WifiOff, label: 'Offline — data unavailable', style: tone.danger } : state === 'demo' ? { icon: CircleHelp, label: 'DEMO DATA — not operational', style: tone.info } : { icon: CircleHelp, label: 'Data state unknown', style: tone.neutral }; const Icon = config.icon; return <div className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold ${config.style}`}><Icon size={15}/><span>{config.label}</span>{message && <span className="font-normal opacity-80">· {message}</span>}</div>; }
export function PreviewControl({ children, reason, onNavigate }: { children: React.ReactNode; reason: string; onNavigate?: () => void }) { return <div className="group relative"><button type="button" disabled={!onNavigate} onClick={onNavigate} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-slate-300 bg-slate-100 px-3 text-xs font-black text-slate-500 disabled:cursor-not-allowed dark:border-slate-700 dark:bg-slate-800 dark:text-slate-400"><LockKeyhole size={14}/>{children}</button><p className="mt-1 text-center text-[10px] text-slate-500">{onNavigate ? 'Opens existing protected tool' : `Preview only · ${reason}`}</p></div>; }
export function Unknown({ label = 'Unavailable' }: { label?: string }) { return <span className="font-mono text-xs text-slate-400">— {label} —</span>; }
export function ActiveBanner({ kind, label, restoring = false }: { kind: 'test' | 'simulation'; label: string; restoring?: boolean }) { return <div data-testid={`active-${kind}-banner`} className={`flex items-center justify-between gap-4 rounded-xl border px-4 py-3 ${kind === 'simulation' ? tone.info : tone.warning}`}><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em]">Active {kind}</p><p className="mt-1 text-sm font-black">{label}</p></div><StatusPill state={restoring ? 'warning' : 'danger'}>{restoring ? 'Restoring' : 'In progress'}</StatusPill></div>; }
