import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {RecoveryWorkflow} from './RecoveryWorkflow';
import {RecoveryPanel} from './RecoveryPanel';
import type {RecoveryReview} from '../core/security/commandRecovery';
const review:RecoveryReview={command:{commandId:'fixture-recovery-command',array:1,string:2,action:'open',reason:'Fixture',state:'reserved',createdAt:1,updatedAt:1,result:null,reviews:[],historical:true},observation:{actual:'open',requested:'open',capturedAt:1000},validUntil:16000};
let now=1000,writes=0,resolve!:()=>void;
const workflow=new RecoveryWorkflow({list:async()=>[review.command],review:async()=>review,record:async intent=>{writes++;assert.equal(intent.confirmed,true);return new Promise(res=>{resolve=res;});}},()=>now);
await workflow.open();assert.equal(writes,0);await workflow.select(review.command.commandId);assert(workflow.canSave());
const html=renderToStaticMarkup(<RecoveryPanel view={workflow.getSnapshot()} canSave={true} disabled={false} onOpen={()=>{}} onClose={()=>{}} onSelect={()=>{}} onSave={()=>{}}/>);
assert.match(html,/Array 1 \/ String 2/);assert.match(html,/keep blocked/);assert.match(html,/no longer queued/);assert.doesNotMatch(html,/>Retry command</);
now=17000;await workflow.save('site-checked');assert.equal(writes,0);
now=1000;const pending=workflow.save('site-checked');await workflow.save('site-checked');assert.equal(writes,1);workflow.close();assert.equal(workflow.getSnapshot().phase,'saving');
workflow.stop();resolve();await pending;assert.equal(workflow.getSnapshot().phase,'closed');
let failedWrites=0;
const failed=new RecoveryWorkflow({list:async()=>[],review:async()=>review,record:async()=>{failedWrites++;throw new Error('timeout');}},()=>1000);
await failed.select(review.command.commandId);await failed.save('follow-up-required');await failed.save('follow-up-required');assert.equal(failedWrites,1);assert.match(failed.getSnapshot().message,/Refresh saved commands/);
let late!:(value:RecoveryReview)=>void;
const stopped=new RecoveryWorkflow({list:async()=>[],review:()=>new Promise(res=>{late=res;}),record:async()=>{throw new Error('No writes');}});
const read=stopped.select(review.command.commandId);stopped.stop();late(review);await read;assert.equal(stopped.getSnapshot().phase,'closed');
console.log('Recovery UI: review-only loading, explicit save, expiry, double-click guard, no retry, logout isolation and rendered warning passed.');
