import { count, finite, list, object, text } from './ProjectionHelpers';

export function buildOperatorProjection(snapshotValue: Readonly<Record<string, unknown>>) {
  const snapshot = object(snapshotValue); const normalized = object(snapshot.normalized); const rollups = object(snapshot.rollups); const strings = list(normalized.strings); const fleet = object(rollups.bessFleetSummary); const feather = object(rollups.featherSummary); const live = object(snapshot.liveStatus);
  const issues = list(normalized.correctiveActions).slice(0, 50).map((item, index) => { const row = object(item); return { id: text(row.id ?? row.code) ?? `issue-${index}`, severity: text(row.severity ?? row.priority) ?? 'info', title: text(row.title ?? row.displayText ?? row.message) ?? 'Operational issue', location: text(row.location ?? row.canonicalKey) ?? 'Site', detail: text(row.detail ?? row.description ?? row.message), source: text(row.source) ?? 'canonical', timestamp: text(row.timestamp ?? row.lastUpdated) }; });
  const arrays = list(rollups.arraySummary).filter((row) => { const n = Number(row?.arrayIndex ?? row?.arrayNumber); return n >= 1 && n <= 8; }).map((value) => { const row = object(value); const arrayIndex = Number(row.arrayIndex ?? row.arrayNumber); const members = strings.filter((item) => Number(item?.arrayIndex ?? item?.arrayNumber) === arrayIndex); return { arrayIndex, health: text(row.health ?? row.operationalState ?? row.status) ?? 'unknown', soc: finite(row.socPct ?? row.soc), power: finite(row.powerKw ?? row.kw), warnings: members.reduce((sum, item) => sum + count(item?.warningCount ?? item?.warnCount), 0), alarms: members.reduce((sum, item) => sum + count(item?.alarmCount), 0), offlineStrings: members.filter((item) => item?.communicating === false).length, staleStrings: members.filter((item) => item?.stale === true || item?.staleData === true).length, thermalRisk: finite(row.maxCellTempC ?? row.maxCellTemperature), availability: finite(row.availabilityPct ?? row.availability) }; });
  const warnings = strings.reduce((sum, row) => sum + count(row?.warningCount ?? row?.warnCount), 0); const alarms = strings.reduce((sum, row) => sum + count(row?.alarmCount), 0); const stale = strings.filter((row) => row?.stale === true || row?.staleData === true).length; const offline = strings.filter((row) => row?.communicating === false).length;
  return { site: { ...object(snapshot.siteIdentity), connectionState: text(live.state), source: text(live.source) }, emsHealth: { state: text(live.state), liveAttempted: live.liveAttempted === true, liveSucceeded: live.liveSucceeded === true, errors: list(live.errors).map(String) }, telemetryTrust: { stale: live.stale === true, cacheUsed: live.cacheUsed === true, ageMs: finite(live.ageMs), lastUpdated: text(live.lastUpdated) }, counts: { activeAlarms: alarms, activeWarnings: warnings, staleDevices: stale, offlineDevices: offline }, siteMetrics: { soc: finite(fleet.systemSocPct ?? fleet.socPct ?? object(rollups.stringSummary).fleetSoc), power: finite(fleet.measuredPowerKw ?? fleet.powerKw ?? object(rollups.pcsSummary).measuredKw), availableCapacity: finite(fleet.availableStoredKWh ?? fleet.availableCapacityKWh) }, arrays, environmentalRisk: { maxCellTemperature: finite(feather.maxCellTempC ?? fleet.maxCellTempC), maxSpaceTemperature: finite(feather.maxSpaceTempC), maxHydrogenPpm: finite(feather.maxHydrogenPpm), featherFaults: count(feather.activeFaultCount) }, prioritizedIssues: issues, activeWorkflows: { maintenance: null, test: object(snapshot.diagnosticSession), simulation: object(snapshot.hvacSimulation), balancer: object(snapshot.balancerTest) }, recentEvents: issues.slice(0, 20) };
}
