import type { CompactStringDiagnostic } from './WorkspaceProjectionTypes';
import { count, finite, list, object, text } from './ProjectionHelpers';

export function compactString(rowValue: unknown, cycleId: number | null): CompactStringDiagnostic | null {
  const source = object(rowValue); const identity = object(source.identity); const row: Record<string, any> = { ...source, controllerIp: source.controllerIp ?? identity.featherIp, energySegmentNumber: source.energySegmentNumber ?? identity.localEsNumber }; const arrayIndex = Number(row.arrayIndex ?? row.arrayNumber ?? identity.arrayIndex); const stringIndex = Number(row.stringIndex ?? row.stringNumber ?? identity.stringNumber);
  if (!Number.isSafeInteger(arrayIndex) || !Number.isSafeInteger(stringIndex)) return null;
  const key = text(row.identity?.canonicalKey ?? row.canonicalKey ?? row.stringKey) ?? `A${arrayIndex}-S${stringIndex}`;
  return { canonicalIdentity: key, publicDisplayKey: `A${arrayIndex}-S${stringIndex}`, arrayIndex, stringIndex, energySegment: finite(row.energySegmentNumber ?? row.energySegmentIndex ?? row.localEsNumber) ?? Math.ceil(stringIndex / 2), controllerIp: text(row.controllerIp ?? row.stringControllerIp ?? row.ipAddress ?? row.deviceIp), connectionState: text(row.connectionState ?? row.stringConnectionState ?? row.operationalState), soc: finite(row.socPct ?? row.soc), measuredVoltage: finite(row.measuredVoltageVdc ?? row.measuredStringVoltage ?? row.measuredVoltage), minVoltage: finite(row.minCellVoltageMv ?? row.minCellVoltage ?? row.cellVoltageMin), maxVoltage: finite(row.maxCellVoltageMv ?? row.maxCellVoltage ?? row.cellVoltageMax), voltageDelta: finite(row.cellVoltageDelta ?? row.deltaCellVoltageMv ?? row.voltageDelta), minTemperature: finite(row.minCellTemperature ?? row.minCellTempC ?? row.cellTempMin), maxTemperature: finite(row.maxCellTemperature ?? row.maxCellTempC ?? row.cellTempMax), temperatureDelta: finite(row.cellTemperatureDelta ?? row.deltaCellTempC ?? row.cellTempDelta), power: finite(row.powerKw ?? row.kw), current: finite(row.currentA ?? row.amps), warningCount: count(row.warningCount ?? row.warnCount), alarmCount: count(row.alarmCount), stale: row.stale === true || row.staleData === true, quality: text(row.quality ?? row.sourceCoverage?.quality) ?? (row.communicating === false ? 'unavailable' : 'good'), cycleId };
}

function compactFeather(value: unknown) { const row = object(value); return { sourceOk: row.sourceOk ?? null, stale: row.isStale ?? null, totalDevices: row.totalDevices ?? null, onlineDevices: row.onlineDevices ?? null, offlineDevices: row.offlineDevices ?? null, lostCommsCount: row.lostCommsCount ?? null, activeWarningCount: row.activeWarningCount ?? null, activeFaultCount: row.activeFaultCount ?? null, maxHydrogenPpm: finite(row.maxHydrogenPpm), maxSpaceTempC: finite(row.maxSpaceTempC), maxCellTempC: finite(row.maxCellTempC) }; }

export function buildTechnicianProjection(snapshotValue: Readonly<Record<string, unknown>>, cycleId: number | null) {
  const snapshot = object(snapshotValue); const normalized = object(snapshot.normalized); const rollups = object(snapshot.rollups);
  const strings = list(normalized.strings).map((row) => compactString(row, cycleId)).filter((row): row is CompactStringDiagnostic => row != null);
  const arrays = Array.from(new Set(strings.map((row) => row.arrayIndex))).sort((a, b) => a - b).map((arrayIndex) => { const rows = strings.filter((row) => row.arrayIndex === arrayIndex); return { arrayIndex, strings: rows.length, warnings: rows.reduce((sum, row) => sum + row.warningCount, 0), alarms: rows.reduce((sum, row) => sum + row.alarmCount, 0), offline: rows.filter((row) => row.connectionState?.toLowerCase().includes('offline')).length, stale: rows.filter((row) => row.stale).length }; });
  const segments = Array.from(new Map(strings.map((row) => [`${row.arrayIndex}:${row.energySegment}`, { arrayIndex: row.arrayIndex, energySegment: row.energySegment, strings: 0, warnings: 0, alarms: 0 }])).values());
  for (const segment of segments) { const rows = strings.filter((row) => row.arrayIndex === segment.arrayIndex && row.energySegment === segment.energySegment); segment.strings = rows.length; segment.warnings = rows.reduce((sum, row) => sum + row.warningCount, 0); segment.alarms = rows.reduce((sum, row) => sum + row.alarmCount, 0); }
  return { site: snapshot.siteIdentity ?? null, acquisitionHealth: snapshot.liveStatus ?? null, activeFaults: list(normalized.correctiveActions).slice(0, 200), correctiveActions: list(normalized.correctiveActions).slice(0, 200), arrays, energySegments: segments, strings, communications: { total: strings.length, offline: strings.filter((row) => row.connectionState?.toLowerCase().includes('offline')).length, stale: strings.filter((row) => row.stale).length }, hvacFeather: compactFeather(rollups.featherSummary), sensors: { summary: object(rollups.sensorsSummary), count: list(normalized.sensors).length }, activeWorkflows: { test: object(snapshot.diagnosticSession), simulation: object(snapshot.hvacSimulation), balancer: object(snapshot.balancerTest) }, recentResults: { fan: [], hvac: [], balancer: [] } };
}
