import React from 'react';
import assert from 'node:assert/strict';
import {renderToStaticMarkup} from 'react-dom/server';
import NotificationReviewPanel,{NotificationGroupRow,NotificationTargetsTable} from './NotificationReviewPanel';
import {buildNotificationReview} from '../server/notifications/notificationReview';
const review=buildNotificationReview([1,2,3].map(string=>({code:'CONTACTOR',title:'Contactors open',severity:'alarm',arrayNumber:1,stringNumber:string})), '2026-09-28T16:00:00Z');
const html=renderToStaticMarkup(<NotificationReviewPanel review={review}/>);
assert.equal((html.match(/<summary/g)||[]).length,2,'only group and source definitions; no target dropdowns');
assert.match(html,/3 affected targets/); assert.match(html,/Unique targets/);
assert.match(html,/Notification severity/); assert.match(html,/Find notification/);
assert.match(html,/aria-label="Battery &amp; equipment issues"/);
assert.match(html,/aria-label="Contactors &amp; rotation"/);
assert(html.indexOf('Contactors open')>html.indexOf('aria-label="Contactors &amp; rotation"'));
const voltageHtml=renderToStaticMarkup(<NotificationReviewPanel review={buildNotificationReview([{code:'2003',severity:'warning',arrayNumber:1,stringNumber:1}],review.capturedAt)}/>);
assert.match(voltageHtml,/String High Voltage Warning/);
assert.match(voltageHtml,/Documented clearing behavior/);
assert.match(voltageHtml,/manual page 44/);
assert.match(voltageHtml,/not confirmation that the condition has cleared/);
assert.match(voltageHtml,/manual labels this a Warning/);
assert(voltageHtml.indexOf('String High Voltage Warning')<voltageHtml.indexOf('aria-label="Contactors &amp; rotation"'));
assert(html.includes('<table')); assert(!html.includes('max-height'));
assert.equal((html.match(/scope="row"/g)||[]).length,3);
assert.match(html,/3 consolidated rows/);
const legacy=renderToStaticMarkup(<NotificationGroupRow group={review.groups[0]} array="all" targetLayout="details"/>);
assert.equal((legacy.match(/<summary/g)||[]).length,4,'previous target details retained as rollback');
const repeated=buildNotificationReview([1,2,3].map(cell=>({code:'1001',arrayNumber:1,stringNumber:2,affected:[{arrayIndex:1,stringIndex:2,batteryPackIndex:3,cellGroupIndex:cell}]})),review.capturedAt);
const condensed=renderToStaticMarkup(<NotificationGroupRow group={repeated.groups[0]} array="all"/>);
assert.equal((condensed.match(/scope="row"/g)||[]).length,1);
assert.match(condensed,/BPC 3 · Cell groups 1, 2, 3/);
assert.equal((condensed.match(/<summary/g)||[]).length,1);
assert.match(renderToStaticMarkup(<NotificationReviewPanel review={review} stale/>),/Retained snapshot/);
assert.match(renderToStaticMarkup(<NotificationReviewPanel/>),/does not mean the site is clear/);
assert.match(renderToStaticMarkup(<NotificationGroupRow group={review.groups[0]} array="1"/>),/Showing Array 1 targets/);
console.log('Notification review presentation tests passed');
const packReview=buildNotificationReview([{code:'2008',arrayNumber:1,stringNumber:2}],review.capturedAt);
packReview.groups[0].tableRows![0].bpcOutliers={quality:'stale',reason:'Retained reading',source:'Cached EMS StringViewer',observedAt:review.capturedAt,ranked:[{bpc:2,voltageV:102,peerAverageV:100,deviationV:2},{bpc:1,voltageV:99,peerAverageV:101,deviationV:-2}]};
const packHtml=renderToStaticMarkup(<NotificationGroupRow group={packReview.groups[0]} array="all"/>);
for(const label of ['Calculated BPC outliers','Controller reported','not controller-confirmed','+2.000','-2.000','stale','Show all BPC comparisons','String-level / BPC not supplied']) assert(packHtml.includes(label),label);
assert.equal((packHtml.match(/scope="row"/g)||[]).length,1,'BPC comparison does not duplicate targets');
assert.equal((packHtml.match(/<summary/g)||[]).length,1,'No per-target dropdowns');
const packRollback=renderToStaticMarkup(<NotificationGroupRow group={packReview.groups[0]} array="all" showMetrics={false}/>);
assert(!packRollback.includes('Calculated BPC outliers'));
const metricGroup=buildNotificationReview([{code:'2008',arrayNumber:1,stringNumber:2}],review.capturedAt,{blockIndex:1,strings:[{
  arrayNumber:1,stringNumber:2,measuredVoltageVdc:1400,minCellVoltageMv:3300,maxCellVoltageMv:3400,sourceTimestampUtc:review.capturedAt
}]}).groups[0];
const metricHtml=renderToStaticMarkup(<NotificationGroupRow group={metricGroup} array="all"/>);
assert.match(metricHtml,/String context/);assert.match(metricHtml,/Cell Δ/);assert.match(metricHtml,/title="Cell Δ \(high − low\): 100 mV"/);
assert.match(metricHtml,/not values captured when the notification triggered/);
assert.match(metricHtml,/not the individual affected BPC or cell/);
assert.equal((metricHtml.match(/<summary/g)||[]).length,1);
assert(!renderToStaticMarkup(<NotificationGroupRow group={metricGroup} array="all" showMetrics={false}/>).includes('String context'));
assert.match(voltageHtml,/aria-label="String measured unavailable"/);
assert.equal((metricHtml.match(/scope="col"/g)||[]).length,7,'target, BPC scope, four metrics and observation columns');
assert.equal((metricHtml.match(/String measured/g)||[]).length,2,'one header and one accessible value title, not a card per target');
assert(!metricHtml.includes('<dl'),'readings are table cells rather than nested metric cards');
const comfortable=renderToStaticMarkup(<NotificationGroupRow group={metricGroup} array="all" compact={false}/>);
assert.match(comfortable,/<dl/);assert.match(comfortable,/100 mV/);
const withoutMetrics=renderToStaticMarkup(<NotificationTargetsTable rows={metricGroup.tableRows!} title={metricGroup.title} showMetrics={false}/>);
assert.equal((withoutMetrics.match(/scope="col"/g)||[]).length,3);
const varied=renderToStaticMarkup(<NotificationTargetsTable title="Mixed evidence" rows={[
  {...metricGroup.tableRows![0],id:'a',source:['source-a'],scope:['BPC 1 · Cell groups 1, 2']},
  {...metricGroup.tableRows![0],id:'b',source:['source-b'],scope:['BPC 2 · Cell groups 3'],metrics:{...metricGroup.tableRows![0].metrics!,quality:'stale',at:null}}
]}/>);
for(const expected of ['source-a','source-b','BPC 1 · Cell groups 1, 2','BPC 2 · Cell groups 3','stale','time unavailable']) assert(varied.includes(expected));
assert.equal((varied.match(/<summary/g)||[]).length,0);
assert.match(condensed,/Array \/ Segment \/ String/);
assert.match(condensed,/BPC \/ Cell groups/);
const condensedRow=condensed.slice(condensed.indexOf('<tbody'),condensed.indexOf('</tbody>'));
assert(!condensedRow.slice(0,condensedRow.indexOf('</th>')).includes('Cell groups'),'BPC scope is not repeated in target identity');
assert.match(condensedRow,/<\/th><td[^>]*><div>BPC 3 · Cell groups 1, 2, 3<\/div><\/td>/,'shared BPC scope stays beside its string, not in the caption');
const multipleBpcs=renderToStaticMarkup(<NotificationTargetsTable title="Multiple BPCs" rows={[{...metricGroup.tableRows![0],scope:['BPC 3 · Cell groups 1, 2','BPC 5 · Cell groups 7, 9']}]} showMetrics={false}/>);
assert.match(multipleBpcs,/<td[^>]*><div>BPC 3 · Cell groups 1, 2<\/div><div>BPC 5 · Cell groups 7, 9<\/div><\/td>/,'each BPC retains its own cell-group association');
const guided=buildNotificationReview([1,2].map(array=>({code:'1001',arrayNumber:array,stringNumber:1,recommendedActions:['Shared test action',`Check Array ${array} sensor`],resolved:{matched:true,matrixEntryId:'test-entry',sourceLabel:'Test guide',recommendedActions:['Read meter'],validationChecks:['Compare telemetry'],clearingCriteria:['Normal reported state']}})),review.capturedAt).groups[0];
const guidedHtml=renderToStaticMarkup(<NotificationGroupRow group={guided} array="all" onEditGuidance={()=>{}}/>);
for(const label of ['Recommended Actions','Validation Checks','Clearing Criteria / required state','Edit Guidance','Test guide','Compare telemetry','Normal reported state']) assert(guidedHtml.includes(label));
assert(guidedHtml.indexOf('Troubleshooting &amp; resolution')<guidedHtml.indexOf('<table'));
assert.equal((guidedHtml.match(/Shared test action/g)||[]).length,1);
assert(!guidedHtml.slice(guidedHtml.indexOf('<tbody'),guidedHtml.indexOf('</tbody>')).includes('Check Array'));
assert.match(guidedHtml,/Applies to: Array 1 \/ String 1/);
const arrayFiltered=renderToStaticMarkup(<NotificationGroupRow group={guided} array="1"/>);
assert(arrayFiltered.includes('Check Array 1 sensor'));assert(!arrayFiltered.includes('Check Array 2 sensor'));
assert.equal((guidedHtml.match(/<summary/g)||[]).length,1,'no new per-target or nested guidance dropdowns');
const advisory=buildNotificationReview([{code:'2008',arrayNumber:1,stringNumber:1,resolved:{matched:false,clearingCriteria:['Generic reset check'],sourceLabel:'Advisory fallback'}}],review.capturedAt).groups[0];
assert.match(renderToStaticMarkup(<NotificationGroupRow group={advisory} array="all"/>),/Generic fallback criteria are not verified fault-specific clearing conditions/);
