import React from "react";
import assert from "node:assert/strict";
import {renderToStaticMarkup} from "react-dom/server";
import PcsOperationalTimeline, {TimelineResults, TimelineRecorderStatus} from "./PcsOperationalTimeline";
import type {TimelineReport} from "../server/history/operationalTimelineModel";
const report: TimelineReport = {from: 0, to: 3600000, site: "Fixture", array: 1, samples: 0, events: [], eventsTruncated: false, points: [], coverage: []};
assert.match(renderToStaticMarkup(<TimelineResults report={report}/>), /No saved observations/);
report.samples = 2; report.coverage = [{label: "Array 1 · PCS 1", stream: "electrical", coverage: "0.3%", longestGap: "59.8 min"}];
report.events = [{at: 0, label: "Array 1 · PCS 1", source: "Direct PCS", message: "DC 1: OPEN → CLOSED"}];
const html = renderToStaticMarkup(<TimelineResults report={report}/>);
assert.match(html, /0.3%/); assert.match(html, /59.8 min/); assert.match(html, /DC 1: OPEN/); assert.match(html, /not command acknowledgments/);
const panel = renderToStaticMarkup(<PcsOperationalTimeline arrays={[1, 2]}/>);
assert.match(panel, /Operational history &amp; incident timeline/); assert(!panel.includes("<table"), "History is collapsed and lazy by default");
report.selectedString = 2;
report.events.unshift({at: 1, label: "Array 1 · String 2", source: "PRIZM command service", kind: "command", commandId: "fixture-command", message: "RESULT — delivery: accepted; readback: not confirmed by command service"});
const commands = renderToStaticMarkup(<TimelineResults report={report}/>);
assert.match(commands, /COMMAND/); assert.match(commands, /OBSERVED/); assert.match(commands, /fixture-command/);
assert.match(commands, /readback: not confirmed/); assert.match(commands, /array-wide commands and PCS context remain included/);
assert.match(commands, /Kobold or other tools are not captured/);
assert.match(commands, /Block-wide EMS app states and power commands are included for every array/);
assert.match(commands, /settings, not measured site power/);
console.log("PCS timeline empty, gap and event presentation passed");
const status = {enabled: true, site: "Fixture", lastSaved: null, error: null, droppedBatches: 1, droppedCommands: 0, retentionDays: 7, pendingBatches: 2, pendingCommands: 1, lastDropReason: "Telemetry queue byte limit reached"};
const queue = renderToStaticMarkup(<TimelineRecorderStatus status={status}/>);
assert.match(queue, /telemetry batches pending: 2/);
assert.match(queue, /command entries pending: 1/);
assert.match(queue, /unsaved \/ incomplete telemetry batches: 1/);
assert.match(queue, /Telemetry queue byte limit reached/);
assert.match(queue, /counters since server start/);
assert.match(renderToStaticMarkup(<TimelineRecorderStatus status={{...status, pendingBatches: undefined}}/>), /telemetry batches pending: unknown/);
console.log("Timeline queue status, loss reason and legacy status compatibility passed");
