import assert from "node:assert/strict";
import React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {reviewReading} from "../server/thermal/thermalReviewPresentation";
import type {ThermalPoint} from "../server/thermal/thermalModel";
import {indexReviewSamples,observationAt} from "./thermalReviewIndex";
import ThermalComparison from "./ThermalComparison";
import ThermalCommandBands from "./ThermalCommandBands";
import {defaultTargetFilters,parseSavedViews,type ThermalSavedState} from "./thermalSavedViewState";
const point:ThermalPoint={at:1000,space:25,supply:20,current:0,rpm:null,cooling:25,heating:15,mode:"Cooling",quality:"Live",commands:{compressor:true,electricHeat:false,reversingValve:false,fanLow:true,fanHigh:false}};
assert.equal(reviewReading(point,"current").valueText,"0.0 A");
assert.equal(reviewReading(point,"current").command,"Cooling","Zero current does not imply no cooling command");
assert.equal(reviewReading({...point,commands:undefined},"current").command,"Unknown");
assert.equal(reviewReading({...point,quality:"Stale"},"current").valueText,"—");
assert.equal(reviewReading({...point,segmentType:"CS",cell:32767},"cell").status,"N/A — no cells");
assert.equal(reviewReading(point,"current",true).command,"Unknown");
const samples=[{id:"a",point:{...point,at:1000},review:reviewReading(point,"current")},{id:"a",point:{...point,at:3000,current:12},review:reviewReading({...point,at:3000,current:12},"current")}];
const index=indexReviewSamples(samples);
assert.equal(observationAt(index.get("a")!,999),undefined);
assert.equal(observationAt(index.get("a")!,2900)?.point.at,1000,"Never borrow a nearer future reading");
assert.equal(observationAt(index.get("a")!,3000)?.point.at,3000);
const compare=(at:number)=>renderToStaticMarkup(<ThermalComparison at={at} ids={["a","missing"]} index={index} label={id=>id} summarized={false}/>);
assert.match(compare(2900),/0.0 A/);
assert.match(compare(2900),/No earlier sample/);
assert.match(compare(125000),/Gap \/ older than 2 min/);
assert.doesNotMatch(compare(125000),/12.0 A/);
const bands=renderToStaticMarkup(<ThermalCommandBands ids={["a"]} index={index} start={1000} end={3000} label={id=>id} summarized/>);
assert.match(bands,/sampled commands only/);
assert.match(bands,/Compressor On/);
const state:ThermalSavedState={metric:"current",overheadMetric:"cell",array:"all",mapMode:"metric",selected:["a"],targetFilters:{...defaultTargetFilters,topPerArray:"1"},reviewFilters:{minimum:1},session:"site",minutes:60,historyDays:7,visibility:{hidden:["a"],only:null},showCommands:true};
const encode=(s:unknown)=>JSON.stringify({version:1,views:[{name:"Test",state:s}]});
assert.deepEqual(parseSavedViews(encode(state))[0].state,state);
assert.equal(parseSavedViews("broken").length,0);
assert.equal(parseSavedViews(encode({...state,metric:"bad"})).length,0);
assert.equal(parseSavedViews(encode({...state,reviewFilters:{minimum:10,maximum:1}})).length,0);
assert.equal(parseSavedViews(encode({...state,visibility:{hidden:["unselected"],only:null}})).length,0);
console.log("Thermal cursor timing, missing/stale data, command fidelity, sampled bands and saved-view validation passed");
