import assert from "node:assert/strict";
import React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {allTracesVisible,traceIsVisible,toggleTrace,retainTraceVisibility} from "./thermalTraceVisibility";
import ThermalTraceLegend from "./ThermalTraceLegend";
const targets=["one","two","three"];
let state=allTracesVisible();
state=toggleTrace(state,"two",targets);
assert.deepEqual(targets,["one","two","three"],"Visibility never mutates selected targets");
assert.equal(traceIsVisible(state,"two"),false);
assert.equal(traceIsVisible(state,"one"),true);
state=toggleTrace(state,"two",targets);assert.deepEqual(state,allTracesVisible());
state={hidden:["three"],only:"two"};
assert.deepEqual(targets.filter(id=>traceIsVisible(state,id)),["two"]);
state=toggleTrace(state,"one",targets);
assert.deepEqual(targets.filter(id=>traceIsVisible(state,id)),["one","two"],"Adding an overlay while solo keeps only the requested pair");
for(const id of ["one","two"])state=toggleTrace(state,id,targets);
assert.equal(targets.filter(id=>traceIsVisible(state,id)).length,0,"All lines may be hidden without losing targets");
assert.deepEqual(retainTraceVisibility({hidden:["one","two"],only:"two"},["one","three"]),{hidden:["one"],only:null});
state=allTracesVisible();assert.equal(targets.filter(id=>traceIsVisible(state,id)).length,3);
const many=Array.from({length:40},(_,i)=>String(i));
state=toggleTrace(allTracesVisible(),"20",many);
assert.equal(traceIsVisible(state,"20"),false,"Hidden state is independent of the displayed 16-trace page");
const markup=renderToStaticMarkup(<ThermalTraceLegend traces={targets.map(id=>({id,label:id,color:"#123456",visible:false,hasData:id!=="three"}))} only={null} hiddenCount={3} onToggle={()=>{}} onOnly={()=>{}} onRestore={()=>{}}/>);
assert.equal((markup.match(/aria-label="Toggle trace/g)||[]).length,3,"All-hidden legend remains recoverable");
assert.equal((markup.match(/aria-pressed="false"/g)||[]).length,6);
assert.match(markup,/Show all overlays/);assert.match(markup,/no data/);
console.log("Thermal legend visibility, isolation, restoration, pagination and accessible rendering tests passed");
