import { immutableBindingValue } from '../telemetry/binding';
export class ObservationMetrics {
  private state = { rebuildRequests: 0, coalescedRebuilds: 0, rebuildExecutions: 0, skippedUnchangedRebuilds: 0, rebuildDurationMs: null as number | null, bindingReadDurationMs: null as number | null, observationCreationDurationMs: null as number | null, stateReductionDurationMs: null as number | null, indexCreationDurationMs: null as number | null, validationDurationMs: null as number | null, snapshotDurationMs: null as number | null, fieldAdapterDurationMs: null as number | null, routeReconstructionDurationMs: null as number | null, parityComparisonDurationMs: null as number | null, observationLookups: 0, graphLookups: 0, estimatedTemporaryAllocations: 0, successfulRebuilds: 0, failedRebuilds: 0, retainedLastKnownGoodUse: 0, observationCountsByDomain: {} as Record<string, number>, countsByQuality: {} as Record<string, number>, missingObservations: 0, duplicateObservations: 0, staleObservations: 0, crossProfileRejections: 0, parityComparisons: 0, parityMismatches: 0, observationRouteUses: 0, hybridRouteUses: 0, legacyRouteUses: 0, automaticFallbacks: 0, fallbackReasons: {} as Record<string, number> };
  request(coalesced: boolean) { this.state.rebuildRequests++; if (coalesced) this.state.coalescedRebuilds++; } execution() { this.state.rebuildExecutions++; } unchanged() { this.state.skippedUnchangedRebuilds++; }
  success(values: Partial<typeof this.state>) { this.state = { ...this.state, ...values, successfulRebuilds: this.state.successfulRebuilds + 1 }; } failure(retained: boolean) { this.state.failedRebuilds++; if (retained) this.state.retainedLastKnownGoodUse++; }
  crossProfile() { this.state.crossProfileRejections++; } parity(mismatches: number) { this.state.parityComparisons++; this.state.parityMismatches += mismatches; }
  routePerformance(values: { fieldAdapterDurationMs: number; reconstructionDurationMs: number; comparisonDurationMs: number; observationLookups: number; graphLookups: number; estimatedTemporaryAllocations: number }) { this.state.fieldAdapterDurationMs = values.fieldAdapterDurationMs; this.state.routeReconstructionDurationMs = values.reconstructionDurationMs; this.state.parityComparisonDurationMs = values.comparisonDurationMs; this.state.observationLookups += values.observationLookups; this.state.graphLookups += values.graphLookups; this.state.estimatedTemporaryAllocations += values.estimatedTemporaryAllocations; }
  route(mode: 'legacy' | 'hybrid' | 'observation') { if (mode === 'legacy') this.state.legacyRouteUses++; else if (mode === 'hybrid') this.state.hybridRouteUses++; else this.state.observationRouteUses++; }
  fallback(reason: string) { this.state.automaticFallbacks++; this.state.fallbackReasons = { ...this.state.fallbackReasons, [reason]: (this.state.fallbackReasons[reason] ?? 0) + 1 }; }
  snapshot() { return immutableBindingValue(this.state); } reset() { this.state = new ObservationMetrics().state; return this.snapshot(); }
}
