import { immutableBindingValue, type TelemetryBindingSnapshot, type TelemetryObservationBinding } from '../telemetry/binding';
import { deterministicObservationId, immutableObservation, observationFingerprint, observationQuality, observationValueType, OBSERVATION_SCHEMA_VERSION } from './ObservationRecord';
import { reduceCurrentStates } from './ObservationState';
import type { ObservationIndexes, ObservationQuality, ObservationReadiness, ObservationRecord, ObservationSnapshot } from './ObservationTypes';

interface MetricSpec { readonly metric: string; readonly aliases: readonly string[]; readonly unit: string | null }
export const STRING_OBSERVATION_METRICS: readonly MetricSpec[] = [
  { metric: 'connectionState', aliases: ['connectionState', 'stringConnectionState', 'communicating'], unit: null }, { metric: 'operationalState', aliases: ['operationalState', 'state'], unit: null }, { metric: 'badReport', aliases: ['badReport', 'isBadReport'], unit: null }, { metric: 'controllerIp', aliases: ['controllerIp', 'ipAddress', 'stringIp'], unit: null },
  { metric: 'soc', aliases: ['soc', 'socPct', 'SOC'], unit: '%' }, { metric: 'power', aliases: ['power', 'kw', 'powerKw'], unit: 'kW' }, { metric: 'current', aliases: ['current', 'amps', 'currentA', 'stringCurrent'], unit: 'A' }, { metric: 'measuredVoltage', aliases: ['measuredVoltage', 'voltageV', 'voltage'], unit: 'V' },
  { metric: 'minCellVoltage', aliases: ['minCellVoltage', 'minimumCellVoltage', 'minCellVoltageMv'], unit: 'mV' }, { metric: 'maxCellVoltage', aliases: ['maxCellVoltage', 'maximumCellVoltage', 'maxCellVoltageMv'], unit: 'mV' }, { metric: 'voltageDelta', aliases: ['voltageDelta', 'voltageDeltaMv'], unit: 'mV' },
  { metric: 'minCellTemperature', aliases: ['minCellTemperature', 'minCellTemp', 'minTempC', 'cellTempMin'], unit: '°C' }, { metric: 'maxCellTemperature', aliases: ['maxCellTemperature', 'maxCellTemp', 'maxTempC', 'cellTempMax'], unit: '°C' }, { metric: 'temperatureDelta', aliases: ['temperatureDelta', 'tempDelta', 'tempDeltaC', 'cellTempDelta', 'cellTemperatureDelta', 'deltaCellTempC'], unit: '°C' },
  { metric: 'contactorState', aliases: ['contactorState', 'contactorStatus', 'contactorsClosed'], unit: null }, { metric: 'rotationState', aliases: ['rotationState', 'rotationStatus', 'outRotation'], unit: null }, { metric: 'warningCount', aliases: ['warningCount', 'warnCount'], unit: 'count' }, { metric: 'alarmCount', aliases: ['alarmCount'], unit: 'count' }, { metric: 'cellGroupCount', aliases: ['cellGroupCount', 'bpcCount'], unit: 'count' }, { metric: 'lastTelemetryTimestamp', aliases: ['lastTelemetryTimestamp', 'timestampUtc', 'timestamp', 'lastUpdatedUtc'], unit: null },
];
export const CONTROLLER_OBSERVATION_METRICS: readonly MetricSpec[] = [
  { metric: 'reachability', aliases: ['reachable', 'connected', 'connectionState'], unit: null }, { metric: 'status', aliases: ['status'], unit: null }, { metric: 'lastCall', aliases: ['lastCall'], unit: null }, { metric: 'controllerStatistics', aliases: ['controllerStatistics'], unit: null }, { metric: 'sourceAge', aliases: ['sourceAge', 'ageMs'], unit: 'ms' }, { metric: 'endpointHealth', aliases: ['endpointHealth', 'health'], unit: null }, { metric: 'stale', aliases: ['stale'], unit: null }, { metric: 'fallbackUsed', aliases: ['fallbackUsed'], unit: null }, { metric: 'acquisitionError', aliases: ['lastError', 'error'], unit: null }, { metric: 'producingCycle', aliases: ['cycleId', 'producingCycleId'], unit: null },
];
const select = (value: Readonly<Record<string, unknown>>, aliases: readonly string[]): { present: boolean; value: unknown; sourceField: string | null } => { for (const alias of aliases) if (Object.prototype.hasOwnProperty.call(value, alias)) return { present: true, value: value[alias], sourceField: alias }; return { present: false, value: undefined, sourceField: null }; };
const count = (values: readonly string[]): Readonly<Record<string, number>> => Object.fromEntries([...new Set(values)].sort().map((value) => [value, values.filter((candidate) => candidate === value).length]));
const readiness = (expectedStates: number, currentStates: number, requiredMetrics: number, missingMetrics: number, extra: readonly string[]): ObservationReadiness => { const blockers = [...extra]; if (currentStates !== expectedStates) blockers.push(`state-count:${currentStates}:expected-${expectedStates}`); if (missingMetrics) blockers.push(`missing-metrics:${missingMetrics}`); return immutableBindingValue({ ready: blockers.length === 0, blockers, expectedStates, currentStates, requiredMetrics, missingMetrics }); };

export class ObservationResolver {
  build(bindingSnapshot: TelemetryBindingSnapshot): ObservationSnapshot {
    const generatedAt = new Date().toISOString(); const observations: ObservationRecord[] = [];
    for (const binding of bindingSnapshot.bindingsByDomain['string-telemetry']) for (const spec of this.completeSpecs(binding, STRING_OBSERVATION_METRICS)) observations.push(this.create(binding, spec, bindingSnapshot.bindingFingerprint, generatedAt));
    for (const binding of bindingSnapshot.bindingsByDomain['controller-health']) for (const spec of this.completeSpecs(binding, CONTROLLER_OBSERVATION_METRICS)) observations.push(this.create(binding, spec, bindingSnapshot.bindingFingerprint, generatedAt));
    const ids = observations.map((value) => value.observationId); const duplicateObservationCount = ids.length - new Set(ids).size; const currentStates = reduceCurrentStates(observations, generatedAt, bindingSnapshot.cycleId, bindingSnapshot.graphFingerprint); const indexes = this.index(observations);
    const countsByQuality = Object.fromEntries(['GOOD', 'DEGRADED', 'STALE', 'MISSING', 'INVALID', 'RETAINED'].map((quality) => [quality, observations.filter((value) => value.quality === quality).length])) as Record<ObservationQuality, number>;
    const stringStates = currentStates.filter((value) => value.objectKind === 'string'); const controllerStates = currentStates.filter((value) => value.objectKind === 'ems-controller'); const stringMissing = Math.max(0, stringStates.length * STRING_OBSERVATION_METRICS.length - observations.filter((value) => value.telemetryDomain === 'string-telemetry' && STRING_OBSERVATION_METRICS.some((spec) => spec.metric === value.metric)).length); const controllerMissing = Math.max(0, controllerStates.length * CONTROLLER_OBSERVATION_METRICS.length - observations.filter((value) => value.telemetryDomain === 'controller-health' && CONTROLLER_OBSERVATION_METRICS.some((spec) => spec.metric === value.metric)).length);
    const readinessExtra = duplicateObservationCount ? [`duplicate-observations:${duplicateObservationCount}`] : [];
    const fingerprint = observationFingerprint({ schema: OBSERVATION_SCHEMA_VERSION, graphFingerprint: bindingSnapshot.graphFingerprint, bindingFingerprint: bindingSnapshot.bindingFingerprint, observations: observations.map((value) => ({ id: value.observationId, quality: value.quality, value: value.value })) });
    return immutableBindingValue({ generatedAt, cycleId: bindingSnapshot.cycleId, graphFingerprint: bindingSnapshot.graphFingerprint, graphSourceFingerprint: bindingSnapshot.graphSourceFingerprint, bindingFingerprint: bindingSnapshot.bindingFingerprint, observationFingerprint: fingerprint, observationSchemaVersion: OBSERVATION_SCHEMA_VERSION, observations, currentStates, countsByObjectKind: count(currentStates.map((value) => value.objectKind)), countsByDomain: count(observations.map((value) => value.telemetryDomain)), countsByMetric: count(observations.map((value) => value.metric)), countsByQuality, staleObservationCount: observations.filter((value) => value.stale).length, missingObservationCount: observations.filter((value) => value.quality === 'MISSING').length, retainedObservationCount: observations.filter((value) => value.retainedLastKnownGood).length, duplicateObservationCount, crossProfileObservationCount: 0, health: bindingSnapshot.health, sourceMetadata: [...bindingSnapshot.sourceMetadata, { bindingFingerprint: bindingSnapshot.bindingFingerprint, observationSchemaVersion: OBSERVATION_SCHEMA_VERSION }], readiness: { 'string-telemetry': readiness(320, stringStates.length, 320 * STRING_OBSERVATION_METRICS.length, stringMissing, [...readinessExtra, ...(!bindingSnapshot.readinessByDomain['string-telemetry'].ready ? ['binding-not-ready'] : [])]), 'controller-health': readiness(1, controllerStates.length, CONTROLLER_OBSERVATION_METRICS.length, controllerMissing, [...readinessExtra, ...(!bindingSnapshot.readinessByDomain['controller-health'].ready ? ['binding-not-ready'] : [])]) }, parity: {}, indexes });
  }

  private create(binding: TelemetryObservationBinding, spec: MetricSpec, bindingFingerprint: string, publishedAt: string): ObservationRecord {
    const selected = select(binding.value, spec.aliases); let value = selected.value;
    if (spec.metric === 'stale' && !selected.present) value = binding.stale; if (spec.metric === 'fallbackUsed' && !selected.present) value = binding.fallbackUsed; if (spec.metric === 'producingCycle' && !selected.present) value = binding.producingCycleId; if (spec.metric === 'sourceAge' && !selected.present) value = binding.ageMs; if (spec.metric === 'endpointHealth' && !selected.present) value = binding.health;
    const present = selected.present || ['stale', 'fallbackUsed', 'producingCycle', 'sourceAge', 'endpointHealth'].includes(spec.metric); const quality = observationQuality(binding, value, present);
    return immutableObservation({ observationId: deterministicObservationId(binding.objectId, binding.telemetryDomain, spec.metric, binding.producingCycleId, binding.sourceFingerprint), objectId: binding.objectId, objectKind: binding.objectKind, canonicalKey: binding.canonicalKey, telemetryDomain: binding.telemetryDomain, metric: spec.metric, value, valueType: observationValueType(value), unit: spec.unit, observedAt: binding.observedAt, acquiredAt: binding.acquiredAt, normalizedAt: binding.normalizedAt, boundAt: binding.publishedAt, publishedAt, ageMs: binding.ageMs, stale: binding.stale, retainedLastKnownGood: binding.retainedLastKnownGood, health: binding.health, confidence: quality.confidence, quality: quality.quality, sourceProviderId: binding.sourceProviderId, sourceEndpoint: binding.sourceEndpoint, sourceFingerprint: binding.sourceFingerprint, authorityProviderId: binding.authorityProviderId, fallbackUsed: binding.fallbackUsed, graphFingerprint: binding.graphFingerprint, graphSourceFingerprint: binding.graphSourceFingerprint, bindingFingerprint, cycleId: binding.cycleId, producingCycleId: binding.producingCycleId, failureCycleId: binding.failureCycleId, metadata: { ...binding.metadata, bindingId: binding.bindingId, sourceField: selected.sourceField, present } });
  }

  private completeSpecs(binding: TelemetryObservationBinding, required: readonly MetricSpec[]): readonly MetricSpec[] {
    const selectedSourceFields = new Set(required.map((spec) => select(binding.value, spec.aliases).sourceField).filter((field): field is string => field !== null)); const requiredMetricNames = new Set(required.map((spec) => spec.metric)); const passthrough = Object.keys(binding.value).filter((key) => !selectedSourceFields.has(key) && !requiredMetricNames.has(key)).sort().map((key) => ({ metric: key, aliases: [key], unit: null })); return [...required, ...passthrough];
  }

  private index(observations: readonly ObservationRecord[]): ObservationIndexes {
    const byObservationId: Record<string, ObservationRecord> = {}; const byObjectId: Record<string, string[]> = {}; const byCanonicalKey: Record<string, string[]> = {}; const byMetric: Record<string, string[]> = {}; const byDomain: Record<string, string[]> = {}; const byQuality = Object.fromEntries(['GOOD', 'DEGRADED', 'STALE', 'MISSING', 'INVALID', 'RETAINED'].map((value) => [value, []])) as Record<ObservationQuality, string[]>; const byArrayString: Record<string, string[]> = {}; const byEnergySegment: Record<string, string[]> = {}; const controllerHealthByObjectId: Record<string, string[]> = {};
    for (const value of observations) { byObservationId[value.observationId] = value; (byObjectId[value.objectId] ??= []).push(value.observationId); (byCanonicalKey[value.canonicalKey] ??= []).push(value.observationId); (byMetric[value.metric] ??= []).push(value.observationId); (byDomain[value.telemetryDomain] ??= []).push(value.observationId); byQuality[value.quality].push(value.observationId); if (value.objectKind === 'string') { const coordinate = `${value.metadata.arrayIndex}:${value.metadata.stringIndex}`; (byArrayString[coordinate] ??= []).push(value.observationId); const segment = String(value.metadata.energySegmentId); (byEnergySegment[segment] ??= []).push(value.observationId); } if (value.objectKind === 'ems-controller') (controllerHealthByObjectId[value.objectId] ??= []).push(value.observationId); }
    return immutableBindingValue({ byObservationId, byObjectId, byCanonicalKey, byMetric, byDomain, byQuality, byArrayString, byEnergySegment, controllerHealthByObjectId });
  }
}
