import { immutableBindingValue, type TelemetryBindingSnapshot } from '../telemetry/binding';
import { ObservationResolver } from './ObservationResolver';
export interface ObservationParityHarnessReport { readonly generatedAt: string; readonly cycleId: number | null; readonly bindings: number; readonly reconstructedBindings: number; readonly fieldsCompared: number; readonly exactMatches: number; readonly fieldMismatches: number; readonly missingBindings: number; readonly extraBindings: number; readonly perFieldMismatchHistogram: Readonly<Record<string, number>>; readonly exampleMismatches: readonly Readonly<Record<string, unknown>>[]; readonly pass: boolean }
const ignored = /^(?:generatedAt|publishedAt|responseDuration|responseDurationMs|profilerDuration|profilerDurationMs)$/i;
const clean = (value: unknown): unknown => Array.isArray(value) ? value.map(clean) : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !ignored.test(key)).map(([key, child]) => [key, clean(child)])) : value;
const encode = (value: unknown): string => value === undefined ? '[undefined]' : value === null ? '[null]' : Array.isArray(value) ? `[${value.map(encode).join(',')}]` : typeof value === 'object' ? `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => `${key}:${encode(child)}`).join(',')}}` : `${typeof value}:${String(value)}`;
export class ObservationParityHarness {
  run(bindingInput: TelemetryBindingSnapshot): ObservationParityHarnessReport {
    const binding = immutableBindingValue(bindingInput); const snapshot = new ObservationResolver().build(binding); const reconstructed = new Map<string, Record<string, unknown>>();
    for (const state of snapshot.currentStates) { const value: Record<string, unknown> = {}; const stateObservations = Object.values(state.observationsByMetric); for (const observation of stateObservations) { const sourceField = observation.metadata.sourceField; const present = observation.metadata.present === true; if (present && typeof sourceField === 'string') value[sourceField] = observation.value; } const metadata = stateObservations[0]?.metadata; if (state.objectKind === 'string') { value.arrayIndex = metadata?.arrayIndex; value.stringIndex = metadata?.stringIndex; } reconstructed.set(state.objectId, value); }
    const original = [...binding.bindingsByDomain['string-telemetry'], ...binding.bindingsByDomain['controller-health']]; let fieldsCompared = 0; let exactMatches = 0; let fieldMismatches = 0; let missingBindings = 0; const histogram: Record<string, number> = {}; const examples: Record<string, unknown>[] = [];
    for (const source of original) { const target = reconstructed.get(source.objectId); if (!target) { missingBindings++; continue; } const keys = [...new Set([...Object.keys(source.value), ...Object.keys(target)])].filter((key) => !ignored.test(key)).sort(); for (const key of keys) { fieldsCompared++; if (encode(clean(source.value[key])) === encode(clean(target[key]))) exactMatches++; else { fieldMismatches++; histogram[key] = (histogram[key] ?? 0) + 1; if (examples.length < 25) examples.push({ objectId: source.objectId, field: key, binding: source.value[key], observation: target[key] }); } } }
    const extraBindings = [...reconstructed.keys()].filter((key) => !original.some((value) => value.objectId === key)).length; const pass = fieldMismatches === 0 && missingBindings === 0 && extraBindings === 0;
    return immutableBindingValue({ generatedAt: new Date().toISOString(), cycleId: binding.cycleId, bindings: original.length, reconstructedBindings: reconstructed.size, fieldsCompared, exactMatches, fieldMismatches, missingBindings, extraBindings, perFieldMismatchHistogram: histogram, exampleMismatches: examples, pass });
  }
}
