import assert from 'node:assert/strict';
import { ObjectGraphBuilder } from '../../core/objectGraph';
import { TelemetryBindingResolver, bindingFingerprint, type TelemetryBindingSnapshot } from '../telemetry/binding';
import { deterministicObservationId, observationQuality } from './ObservationRecord';
import { ObservationParityHarness } from './ObservationParityHarness';
import { ObservationResolver, STRING_OBSERVATION_METRICS } from './ObservationResolver';
import { ObservationRuntime } from './ObservationRuntime';

const arrays = Array.from({ length: 8 }, (_, index) => ({ arrayIndex: index + 1 })); const segments = arrays.flatMap(({ arrayIndex }) => Array.from({ length: 8 }, (_, index) => ({ arrayIndex, energySegmentIndex: index + 1 }))); const graphStrings = arrays.flatMap(({ arrayIndex }) => Array.from({ length: 40 }, (_, index) => ({ arrayIndex, stringIndex: index + 1, energySegmentIndex: Math.floor(index / 5) + 1 })));
const graph = new ObjectGraphBuilder({ now: () => new Date('2026-07-15T00:00:00Z') }).build({ site: { siteId: 'BHE0020', name: 'BHE' }, arrays, energySegments: segments, strings: graphStrings, emsController: { deviceIp: '10.0.0.3', port: 8080, turtlePath: '/turtle' } }).snapshot('2026-07-15T00:00:00Z');
const rows = graphStrings.map(({ arrayIndex, stringIndex }) => ({ arrayIndex, stringIndex, connectionState: 'ONLINE', operationalState: 'NORMAL', badReport: false, controllerIp: `10.0.${arrayIndex}.${stringIndex}`, soc: stringIndex, power: 1.25, current: 2.5, measuredVoltage: 1400, minCellVoltage: 3300, maxCellVoltage: 3340, voltageDelta: 40, minCellTemperature: 24, maxCellTemperature: 29, temperatureDelta: 5, contactorState: 'CLOSED', rotationState: 'IN', warningCount: 0, alarmCount: 0, cellGroupCount: 12, lastTelemetryTimestamp: '2026-07-15T00:00:00Z' }));
async function binding(cycleId = 81, overrides: Record<string, unknown> = {}): Promise<TelemetryBindingSnapshot> { return new TelemetryBindingResolver().build({ graph, graphFingerprint: 'graph-current', graphSourceFingerprint: 'graph-source', graphHealthy: true, graphCycleId: cycleId, profileIdentity: 'profile', telemetryProfileIdentity: 'profile', cycleId, capturedAt: '2026-07-15T00:00:00Z', strings: rows.map((row) => ({ ...row, ...overrides })), controllerHealth: { reachable: true, status: { state: 'OK' }, lastCall: { state: 'OK' }, controllerStatistics: { calls: 12 }, sourceAge: 10, endpointHealth: { healthy: true }, stale: false, fallbackUsed: false, lastError: null, cycleId }, authorities: { 'string-telemetry': { chosenProviderId: 'turtle', stale: false }, 'controller-health': { chosenProviderId: 'turtle', stale: false } }, providerHealth: { turtle: { healthy: true } } }); }
const source = await binding(); const sourceBefore = structuredClone(source); const graphBefore = structuredClone(graph); const snapshot = new ObservationResolver().build(source);
assert.equal(snapshot.currentStates.filter((value) => value.objectKind === 'string').length, 320); assert.equal(snapshot.currentStates.filter((value) => value.objectKind === 'ems-controller').length, 1); assert.ok(snapshot.countsByDomain['string-telemetry'] >= 320 * STRING_OBSERVATION_METRICS.length); for (const spec of STRING_OBSERVATION_METRICS) assert.equal(snapshot.countsByMetric[spec.metric], 320); assert.equal(snapshot.duplicateObservationCount, 0); assert.equal(snapshot.readiness['string-telemetry'].ready, true); assert.equal(snapshot.readiness['controller-health'].ready, true);
const firstString = snapshot.currentStates.find((value) => value.objectKind === 'string')!; assert.equal(firstString.observationsByMetric.soc.value, 1); assert.equal(firstString.observationsByMetric.soc.valueType, 'number'); assert.equal(firstString.observationsByMetric.soc.unit, '%'); assert.equal(firstString.observationsByMetric.badReport.valueType, 'boolean'); assert.equal(firstString.observationsByMetric.soc.quality, 'GOOD'); assert.equal(firstString.observationsByMetric.soc.confidence, 1);
assert.equal(deterministicObservationId('a', 'd', 'm', 1, 's'), deterministicObservationId('a', 'd', 'm', 1, 's')); assert.equal(new ObservationResolver().build(source).observationFingerprint, snapshot.observationFingerprint); assert.equal(Object.isFrozen(snapshot), true); assert.equal(Object.isFrozen(snapshot.indexes.byObservationId), true); assert.equal(Object.isFrozen(firstString), true); assert.deepEqual(source, sourceBefore); assert.deepEqual(graph, graphBefore);
const nullBinding = await binding(82, { soc: null }); const nullObservation = new ObservationResolver().build(nullBinding).currentStates.find((value) => value.objectKind === 'string')!.observationsByMetric.soc; assert.equal(nullObservation.value, null); assert.equal(nullObservation.valueType, 'null'); assert.equal(nullObservation.quality, 'GOOD');
const missingInput = structuredClone(await binding()); delete (missingInput.bindingsByDomain['string-telemetry'][0].value as Record<string, unknown>).badReport; const missingSnapshot = new ObservationResolver().build(missingInput); assert.equal(missingSnapshot.missingObservationCount, 1); assert.equal(missingSnapshot.readiness['string-telemetry'].ready, true, 'explicit MISSING observation still satisfies metric-record coverage');
const baseObservationBinding = source.bindingsByDomain['string-telemetry'][0]; const fallbackBinding = { ...baseObservationBinding, fallbackUsed: true }; assert.equal(observationQuality(fallbackBinding, 1, true).quality, 'DEGRADED'); const retainedBinding = { ...fallbackBinding, retainedLastKnownGood: true }; assert.equal(observationQuality(retainedBinding, 1, true).quality, 'RETAINED'); const staleBinding = { ...fallbackBinding, retainedLastKnownGood: false, stale: true }; assert.equal(observationQuality(staleBinding, 1, true).quality, 'STALE'); assert.equal(observationQuality(fallbackBinding, undefined, false).quality, 'MISSING'); assert.equal(observationQuality(fallbackBinding, Number.NaN, true).quality, 'INVALID');
const duplicateInput = { ...source, bindingsByDomain: { ...source.bindingsByDomain, 'string-telemetry': [...source.bindingsByDomain['string-telemetry'], source.bindingsByDomain['string-telemetry'][0]] } }; assert.ok(new ObservationResolver().build(duplicateInput).duplicateObservationCount > 0);
const sameSnapshotParity = new ObservationParityHarness().run(source); assert.equal(sameSnapshotParity.pass, true, JSON.stringify(sameSnapshotParity));

let calls = 0; let release: (() => void) | undefined; let current = source; const runtime = new ObservationRuntime({ collect: async () => { calls++; if (calls === 1) await new Promise<void>((resolve) => { release = resolve; }); return { bindingSnapshot: current, currentGraphFingerprint: current.graphFingerprint, graphHealthy: true }; } }); const one = runtime.requestObservationRebuild('one'); const two = runtime.requestObservationRebuild('two'); release!(); const [oneResult, twoResult] = await Promise.all([one, two]); assert.equal(calls, 1); assert.equal(oneResult.observationFingerprint, twoResult.observationFingerprint); assert.equal(runtime.metrics.snapshot().coalescedRebuilds, 1); await runtime.requestObservationRebuild('unchanged'); assert.equal(runtime.metrics.snapshot().skippedUnchangedRebuilds, 1);
current = await binding(83, { soc: 99 }); const changed = await runtime.requestObservationRebuild('binding-change'); assert.notEqual(changed.bindingFingerprint, oneResult.bindingFingerprint); const goodProducing = changed.observations[0].producingCycleId; const failingCycle = current.cycleId!; const mismatchRuntime = new ObservationRuntime({ collect: async () => ({ bindingSnapshot: current, currentGraphFingerprint: 'different-graph', graphHealthy: true }) }); (mismatchRuntime as unknown as { snapshot: ObservationRuntime['getLatestObservationSnapshot'] extends () => infer T ? T : never }).snapshot = changed; const retained = await mismatchRuntime.requestObservationRebuild('mismatch'); assert.equal(retained.observations[0].producingCycleId, goodProducing); assert.equal(retained.observations[0].failureCycleId, failingCycle); assert.equal(retained.observations[0].quality, 'RETAINED'); assert.equal(retained.readiness['string-telemetry'].ready, false);
const originalMode = process.env.PRIZM_OBSERVATION_MODE; const originalForce = process.env.PRIZM_OBSERVATION_FORCE_LEGACY; const originalDisable = process.env.PRIZM_OBSERVATION_DISABLE; process.env.PRIZM_OBSERVATION_MODE = 'observation'; process.env.PRIZM_OBSERVATION_FORCE_LEGACY = 'true'; assert.equal(runtime.effectiveMode, 'legacy'); process.env.PRIZM_OBSERVATION_FORCE_LEGACY = 'false'; process.env.PRIZM_OBSERVATION_DISABLE = 'true'; assert.equal(runtime.effectiveMode, 'legacy'); delete process.env.PRIZM_OBSERVATION_DISABLE; assert.equal(runtime.effectiveMode, 'observation'); if (originalMode === undefined) delete process.env.PRIZM_OBSERVATION_MODE; else process.env.PRIZM_OBSERVATION_MODE = originalMode; if (originalForce === undefined) delete process.env.PRIZM_OBSERVATION_FORCE_LEGACY; else process.env.PRIZM_OBSERVATION_FORCE_LEGACY = originalForce; if (originalDisable === undefined) delete process.env.PRIZM_OBSERVATION_DISABLE; else process.env.PRIZM_OBSERVATION_DISABLE = originalDisable;
for (let index = 0; index < 105; index++) runtime.parity.compare('GET /api/local/strings', { data: [] }, runtime.getLatestObservationSnapshot()!); assert.equal(runtime.parity.report().history.length, 100); runtime.resetParityHistory(); assert.equal(runtime.parity.report().history.length, 0);
const promotionRuntime = new ObservationRuntime({ collect: async () => ({ bindingSnapshot: source, currentGraphFingerprint: source.graphFingerprint, graphHealthy: true }) }, new ObservationResolver(), { getGraph: async () => graph }); const routePayload = { cycleId: source.cycleId, strings: rows }; const routeBefore = structuredClone(routePayload); process.env.PRIZM_OBSERVATION_MODE = 'observation'; delete process.env.PRIZM_OBSERVATION_FORCE_LEGACY; const promoted = await promotionRuntime.observeRoute('GET /api/local/strings/dashboard', routePayload); assert.deepEqual(promoted, routeBefore); assert.deepEqual(routePayload, routeBefore); assert.notEqual(promoted, routePayload); assert.equal(promotionRuntime.metrics.snapshot().observationRouteUses, 1); process.env.PRIZM_OBSERVATION_MODE = 'hybrid'; const hybrid = await promotionRuntime.observeRoute('GET /api/local/strings/dashboard', routePayload); assert.equal(hybrid, routePayload); assert.equal(promotionRuntime.metrics.snapshot().hybridRouteUses, 1); const changedRoute = structuredClone(routePayload); changedRoute.strings[0].soc = 999; await promotionRuntime.observeRoute('GET /api/local/strings/dashboard', changedRoute); assert.ok(promotionRuntime.metrics.snapshot().automaticFallbacks > 0); process.env.PRIZM_OBSERVATION_MODE = 'observation'; process.env.PRIZM_OBSERVATION_FORCE_LEGACY = 'true'; assert.equal(await promotionRuntime.observeRoute('GET /api/local/strings/dashboard', routePayload), routePayload); assert.ok(promotionRuntime.metrics.snapshot().legacyRouteUses > 0); if (originalMode === undefined) delete process.env.PRIZM_OBSERVATION_MODE; else process.env.PRIZM_OBSERVATION_MODE = originalMode; if (originalForce === undefined) delete process.env.PRIZM_OBSERVATION_FORCE_LEGACY; else process.env.PRIZM_OBSERVATION_FORCE_LEGACY = originalForce;
console.log('Observation runtime tests passed');
