import { immutableBindingValue } from '../telemetry/binding';
import type { ObservationSnapshot } from './ObservationTypes';
export type ObservationRoute = 'GET /api/local/strings' | 'GET /api/local/strings/dashboard' | 'GET /api/local/site-operations/summary' | 'GET /api/local/connection';
export interface ObservationParityResult { readonly route: ObservationRoute; readonly comparedAt: string; readonly matches: number; readonly mismatches: number; readonly missingObservations: number; readonly extraObservations: number; readonly fieldMismatchHistogram: Readonly<Record<string, number>>; readonly samples: readonly string[]; readonly exact: boolean }
const rows = (payload: unknown): readonly Readonly<Record<string, unknown>>[] => { const root = payload && typeof payload === 'object' ? payload as Record<string, unknown> : {}; if (Array.isArray(root.data)) return root.data; if (Array.isArray(root.strings)) return root.strings; const summary = root.stringSummary && typeof root.stringSummary === 'object' ? root.stringSummary as Record<string, unknown> : {}; return Array.isArray(summary.tableRows) ? summary.tableRows : []; };
const positive = (value: unknown) => { const number = Number(value); return Number.isSafeInteger(number) && number > 0 ? number : null; };
const aliases: Readonly<Record<string, readonly string[]>> = { connectionState: ['connectionState', 'communicating'], operationalState: ['operationalState', 'state'], badReport: ['badReport'], controllerIp: ['controllerIp', 'ipAddress'], soc: ['soc', 'socPct'], power: ['power', 'kw', 'powerKw'], current: ['current', 'amps', 'currentA', 'stringCurrent'], measuredVoltage: ['measuredVoltage', 'voltageV'], minCellVoltage: ['minCellVoltage', 'minCellVoltageMv'], maxCellVoltage: ['maxCellVoltage', 'maxCellVoltageMv'], voltageDelta: ['voltageDelta', 'voltageDeltaMv'], minCellTemperature: ['minCellTemperature', 'minCellTemp', 'minTempC'], maxCellTemperature: ['maxCellTemperature', 'maxCellTemp', 'maxTempC'], temperatureDelta: ['temperatureDelta', 'tempDelta', 'tempDeltaC'], contactorState: ['contactorState', 'contactorStatus', 'contactorsClosed'], rotationState: ['rotationState', 'rotationStatus', 'outRotation'], warningCount: ['warningCount', 'warnCount'], alarmCount: ['alarmCount'], cellGroupCount: ['cellGroupCount', 'bpcCount'], lastTelemetryTimestamp: ['lastTelemetryTimestamp', 'timestampUtc', 'timestamp', 'lastUpdatedUtc'], reachability: ['reachability', 'reachable', 'connected', 'connectionState'], status: ['status'], lastCall: ['lastCall'], controllerStatistics: ['controllerStatistics'], sourceAge: ['sourceAge', 'ageMs'], endpointHealth: ['endpointHealth'], stale: ['stale', 'staleData'], fallbackUsed: ['fallbackUsed'], acquisitionError: ['acquisitionError', 'lastError', 'error'], producingCycle: ['producingCycle', 'cycleId', 'producingCycleId'] };
const read = (value: Readonly<Record<string, unknown>>, names: readonly string[]): { found: boolean; value: unknown } => { for (const name of names) if (Object.prototype.hasOwnProperty.call(value, name)) return { found: true, value: value[name] }; return { found: false, value: undefined }; };
const equal = (left: unknown, right: unknown) => Object.is(left, right) || JSON.stringify(left) === JSON.stringify(right);
export class ObservationParity {
  private history: ObservationParityResult[] = [];
  compare(route: ObservationRoute, payload: unknown, snapshot: ObservationSnapshot): ObservationParityResult {
    let matches = 0; let mismatches = 0; let missingObservations = 0; let extraObservations = 0; const histogram: Record<string, number> = {}; const samples: string[] = []; const fail = (field: string, sample: string) => { mismatches++; histogram[field] = (histogram[field] ?? 0) + 1; if (samples.length < 25) samples.push(sample); };
    if (route === 'GET /api/local/connection') { const state = snapshot.currentStates.find((value) => value.objectKind === 'ems-controller'); const root = payload && typeof payload === 'object' ? payload as Readonly<Record<string, unknown>> : {}; if (!state) { missingObservations++; fail('$controller', 'controller-state-missing'); } else { const connection = state.observationsByMetric.connection?.value; const boundRoute = connection && typeof connection === 'object' && !Array.isArray(connection) ? connection as Readonly<Record<string, unknown>> : {}; for (const [field, value] of Object.entries(root)) { if (!Object.prototype.hasOwnProperty.call(boundRoute, field)) continue; if (equal(value, boundRoute[field])) matches++; else fail(field, `controller-field:${field}`); } } }
    else { const routeRows = rows(payload); const states = snapshot.currentStates.filter((value) => value.objectKind === 'string'); if (routeRows.length !== states.length) { const delta = routeRows.length - states.length; if (delta > 0) extraObservations += delta; else missingObservations += -delta; fail('$rows', `row-count:${routeRows.length}:${states.length}`); } routeRows.forEach((row, index) => { const arrayIndex = positive(row.arrayIndex ?? row.arrayNumber); const stringIndex = positive(row.stringIndex ?? row.stringNumber); const state = snapshot.currentStates.find((value) => value.objectKind === 'string' && Number(value.observationsByMetric.soc?.metadata.arrayIndex) === arrayIndex && Number(value.observationsByMetric.soc?.metadata.stringIndex) === stringIndex); if (!state) { missingObservations++; fail('$identity', `missing:${arrayIndex}:${stringIndex}`); return; } if (states[index]?.objectId !== state.objectId) fail('$order', `order:${arrayIndex}:${stringIndex}`); else matches++; for (const [metric, observation] of Object.entries(state.observationsByMetric)) { const candidate = read(row, aliases[metric] ?? [metric]); if (!candidate.found && observation.quality === 'MISSING') continue; if (!candidate.found) continue; if (equal(candidate.value, observation.value)) matches++; else fail(metric, `field:${arrayIndex}:${stringIndex}:${metric}`); } }); }
    const result = immutableBindingValue({ route, comparedAt: new Date().toISOString(), matches, mismatches, missingObservations, extraObservations, fieldMismatchHistogram: histogram, samples, exact: mismatches === 0 }); this.history.push(result); if (this.history.length > 100) this.history.splice(0, this.history.length - 100); return result;
  }
  report() { const histogram: Record<string, number> = {}; for (const item of this.history) for (const [field, count] of Object.entries(item.fieldMismatchHistogram)) histogram[field] = (histogram[field] ?? 0) + count; return immutableBindingValue({ comparisons: this.history.length, matches: this.history.reduce((sum, value) => sum + value.matches, 0), mismatches: this.history.reduce((sum, value) => sum + value.mismatches, 0), missingObservations: this.history.reduce((sum, value) => sum + value.missingObservations, 0), extraObservations: this.history.reduce((sum, value) => sum + value.extraObservations, 0), fieldMismatchHistogram: histogram, comparisonTimestamp: this.history.at(-1)?.comparedAt ?? null, byRoute: Object.fromEntries([...new Set(this.history.map((value) => value.route))].map((route) => [route, { comparisons: this.history.filter((value) => value.route === route).length, mismatches: this.history.filter((value) => value.route === route).reduce((sum, value) => sum + value.mismatches, 0) }])), byDomain: { 'string-telemetry': { mismatches: this.history.filter((value) => value.route !== 'GET /api/local/connection').reduce((sum, value) => sum + value.mismatches, 0) }, 'controller-health': { mismatches: this.history.filter((value) => value.route === 'GET /api/local/connection').reduce((sum, value) => sum + value.mismatches, 0) } }, samples: this.history.flatMap((value) => value.samples.map((sample) => ({ route: value.route, sample }))).slice(-25), history: this.history }); }
  reset() { this.history = []; return this.report(); }
}
