import { immutableBindingValue } from '../telemetry/binding';
import type { StringRouteVariant } from './StringRouteObservationAdapter';

export interface StringRouteMismatch { readonly row: string; readonly field: string; readonly legacy: unknown; readonly reconstructed: unknown; readonly reason: 'identity' | 'missing' | 'extra' | 'value' | 'type' | 'presence' }
export interface StringRouteParityResult { readonly route: StringRouteVariant; readonly legacyRowCount: number; readonly reconstructedRowCount: number; readonly fieldsCompared: number; readonly exactMatches: number; readonly fieldMismatches: number; readonly identityMismatches: number; readonly fieldPresenceMismatches: number; readonly typeMismatches: number; readonly nullUndefinedMissingMismatches: number; readonly missingRows: number; readonly extraRows: number; readonly duplicates: { readonly legacy: number; readonly reconstructed: number }; readonly exactObjectMatches: number; readonly mismatchHistogram: Readonly<Record<string, number>>; readonly examples: readonly StringRouteMismatch[]; readonly comparisonDurationMs: number; readonly pass: boolean }
const rows = (variant: StringRouteVariant, payload: unknown): readonly Readonly<Record<string, unknown>>[] => { const root = payload && typeof payload === 'object' ? payload as Record<string, unknown> : {}; if (variant === 'local-strings') return Array.isArray(root.data) ? root.data : []; if (variant === 'strings-dashboard') return Array.isArray(root.strings) ? root.strings : []; const summary = root.stringSummary && typeof root.stringSummary === 'object' ? root.stringSummary as Record<string, unknown> : {}; return Array.isArray(summary.tableRows) ? summary.tableRows : []; };
const key = (row: Readonly<Record<string, unknown>>) => `${row.arrayIndex ?? row.arrayNumber}:${row.stringIndex ?? row.stringNumber}`;
const type = (value: unknown) => value === undefined ? 'undefined' : value === null ? 'null' : Array.isArray(value) ? 'array' : typeof value;
const encode = (value: unknown): string => value === undefined ? '[undefined]' : value === null ? '[null]' : Array.isArray(value) ? `[${value.map(encode).join(',')}]` : typeof value === 'object' ? `{${Object.keys(value as object).sort().map((field) => `${JSON.stringify(field)}:${encode((value as Record<string, unknown>)[field])}`).join(',')}}` : `${typeof value}:${String(value)}`;
const duplicates = (values: readonly Readonly<Record<string, unknown>>[]) => values.length - new Set(values.map(key)).size;

export class StringRouteObservationParity {
  compare(route: StringRouteVariant, legacyPayload: unknown, reconstructedPayload: unknown): StringRouteParityResult {
    const started = performance.now(); const legacy = rows(route, legacyPayload); const reconstructed = rows(route, reconstructedPayload); const histogram: Record<string, number> = {}; const examples: StringRouteMismatch[] = [];
    let fieldsCompared = 0; let exactMatches = 0; let fieldMismatches = 0; let identityMismatches = 0; let fieldPresenceMismatches = 0; let typeMismatches = 0; let nullUndefinedMissingMismatches = 0; let missingRows = 0; let extraRows = 0; let exactObjectMatches = 0;
    const fail = (entry: StringRouteMismatch) => { fieldMismatches++; histogram[entry.field] = (histogram[entry.field] ?? 0) + 1; if (examples.length < 25) examples.push(entry); };
    for (let index = 0; index < Math.max(legacy.length, reconstructed.length); index++) if (legacy[index] && reconstructed[index] && key(legacy[index]) !== key(reconstructed[index])) { identityMismatches++; fail({ row: String(index), field: '$identity', legacy: key(legacy[index]), reconstructed: key(reconstructed[index]), reason: 'identity' }); }
    const rightByKey = new Map(reconstructed.map((row) => [key(row), row]));
    for (const left of legacy) { const id = key(left); const right = rightByKey.get(id); if (!right) { missingRows++; fail({ row: id, field: '$row', legacy: left, reconstructed: undefined, reason: 'missing' }); continue; } if (encode(left) === encode(right)) exactObjectMatches++; const keys = [...new Set([...Object.keys(left), ...Object.keys(right)])]; for (const field of keys) { fieldsCompared++; const lp = Object.prototype.hasOwnProperty.call(left, field); const rp = Object.prototype.hasOwnProperty.call(right, field); if (lp !== rp) { fieldPresenceMismatches++; if ((!lp || left[field] === undefined || left[field] === null) && (!rp || right[field] === undefined || right[field] === null)) nullUndefinedMissingMismatches++; fail({ row: id, field, legacy: left[field], reconstructed: right[field], reason: 'presence' }); continue; } const lt = type(left[field]); const rt = type(right[field]); if (lt !== rt) { typeMismatches++; if (['undefined', 'null'].includes(lt) || ['undefined', 'null'].includes(rt)) nullUndefinedMissingMismatches++; fail({ row: id, field, legacy: left[field], reconstructed: right[field], reason: 'type' }); continue; } if (Object.is(left[field], right[field]) || encode(left[field]) === encode(right[field])) exactMatches++; else fail({ row: id, field, legacy: left[field], reconstructed: right[field], reason: 'value' }); } }
    const leftKeys = new Set(legacy.map(key)); for (const right of reconstructed) if (!leftKeys.has(key(right))) { extraRows++; fail({ row: key(right), field: '$row', legacy: undefined, reconstructed: right, reason: 'extra' }); }
    const duplicateCounts = { legacy: duplicates(legacy), reconstructed: duplicates(reconstructed) }; const pass = fieldMismatches === 0 && identityMismatches === 0 && missingRows === 0 && extraRows === 0 && duplicateCounts.legacy === 0 && duplicateCounts.reconstructed === 0;
    return immutableBindingValue({ route, legacyRowCount: legacy.length, reconstructedRowCount: reconstructed.length, fieldsCompared, exactMatches, fieldMismatches, identityMismatches, fieldPresenceMismatches, typeMismatches, nullUndefinedMissingMismatches, missingRows, extraRows, duplicates: duplicateCounts, exactObjectMatches, mismatchHistogram: histogram, examples, comparisonDurationMs: performance.now() - started, pass });
  }
}
