import assert from 'node:assert/strict';
import { ObjectGraphBuilder } from '../../core/objectGraph';
import { buildStringBucketSummary } from '../siteOperations';
import { TelemetryBindingResolver } from '../telemetry/binding';
import { ObservationResolver } from './ObservationResolver';
import { StringRouteObservationAdapter, createStringRouteFieldAdapterRegistry } from './StringRouteObservationAdapter';
import { StringRouteObservationParity } from './StringRouteObservationParity';
import { StringRouteObservationParityHarness } from './StringRouteObservationParityHarness';

const graph = new ObjectGraphBuilder({ now: () => new Date('2026-07-15T00:00:00Z') }).build({ site: { siteId: 'BHE0020', name: 'BHE' }, arrays: [{ arrayIndex: 1 }], energySegments: [{ arrayIndex: 1, energySegmentIndex: 1 }], strings: [1, 2, 3].map((stringIndex) => ({ arrayIndex: 1, stringIndex, energySegmentIndex: 1 })) }).snapshot('2026-07-15T00:00:00Z');
const rows = [1, 2, 3].map((stringIndex) => ({ arrayIndex: 1, stringIndex, arrayNumber: 1, stringNumber: stringIndex, stringKey: `A1-S${stringIndex}`, id: `A1-S${stringIndex}`, timestamp: `2026-07-15T00:00:0${stringIndex}Z`, datetime: '', connectionState: 'Online', stringConnectionState: 'Online', communicating: true, soc: 50 + stringIndex, socPct: 50 + stringIndex, kw: 2, kwh: 3, ah: 4, calculatedVoltage: 1000, measuredVoltage: 1001, busVoltage: 1002, stringCurrent: 5, amps: 5, ctCurrent1: null, ctCurrent2: undefined, contactorsCloseExpected: true, positiveContactorClosed: true, negativeContactorClosed: true, contactorMismatch: false, recloseCount: 0, outRotation: false, rotationStatus: 'IN', maxCellTemp: 30, minCellTemp: 20, avgCellTemp: 25, maxCellTemperature: 30, minCellTemperature: 20, avgCellTemperature: 25, cellTemperatureDelta: 10, tempDelta: 10, maxCellVoltage: 3.4, minCellVoltage: 3.3, avgCellVoltage: 3.35, cellVoltageDelta: 0.1, voltageDelta: 1, alarmCount: 0, alarms: [], warningCount: 0, warnCount: 0, warnings: [], warns: [], lastFanCommand: 'Unknown', location: `R1-Rack${stringIndex}`, ipAddress: `10.0.1.${stringIndex}`, stringControllerIp: `10.0.1.${stringIndex}`, entityToken: `token-${stringIndex}`, badReport: false, bpcCount: 12, optionalUndefined: undefined }));
const binding = await new TelemetryBindingResolver().build({ graph, graphFingerprint: 'graph', graphSourceFingerprint: 'source', graphHealthy: true, graphCycleId: 91, profileIdentity: null, telemetryProfileIdentity: null, cycleId: 91, capturedAt: '2026-07-15T00:00:00Z', strings: rows, controllerHealth: null, authorities: { 'string-telemetry': { chosenProviderId: 'turtle', stale: false } }, providerHealth: { turtle: { healthy: true } } });
const snapshot = new ObservationResolver().build(binding); const sourceBefore = structuredClone(rows); const observationBefore = structuredClone(snapshot); const graphBefore = structuredClone(graph);
const localRows = rows.map((row) => ({ arrayIndex: row.arrayIndex, stringIndex: row.stringIndex, stringKey: `ST:BHE0020:A${row.arrayIndex}:S${row.stringIndex}`, timestamp: row.timestamp, datetime: row.datetime, connectionState: row.connectionState, soc: row.soc, kw: row.kw, kwh: row.kwh, ah: row.ah, calculatedVoltage: row.calculatedVoltage, measuredVoltage: row.measuredVoltage, dcBusVoltage: row.busVoltage, stringCurrent: row.stringCurrent, ctCurrent1: row.ctCurrent1, ctCurrent2: null, contactorsCloseExpected: row.contactorsCloseExpected, positiveContactorClosed: row.positiveContactorClosed, negativeContactorClosed: row.negativeContactorClosed, contactorMismatch: row.contactorMismatch, recloseCount: row.recloseCount, outRotation: row.outRotation, maxCellTemp: row.maxCellTemp, minCellTemp: row.minCellTemp, avgCellTemp: row.avgCellTemp, tempDelta: row.tempDelta, maxCellVoltage: row.maxCellVoltage, minCellVoltage: row.minCellVoltage, avgCellVoltage: row.avgCellVoltage, voltageDelta: row.cellVoltageDelta, alarmCount: row.alarmCount, alarms: row.alarms, warnCount: row.warnCount, warns: row.warns, lastFanCommand: row.lastFanCommand, location: row.location, ipAddress: row.ipAddress, entityToken: row.entityToken }));
const legacyResponses = { 'local-strings': { source: 'same-cycle', cycleId: 91, data: localRows }, 'strings-dashboard': { cycleId: 91, strings: rows }, 'site-operations': { cycleId: 91, stringSummary: buildStringBucketSummary(rows) } } as const;
const report = new StringRouteObservationParityHarness().run({ normalizedRows: rows, observationSnapshot: snapshot, graph, legacyResponses });
assert.equal(report.pass, true, JSON.stringify(report)); for (const route of Object.values(report.routes)) { assert.equal(route.fieldMismatches, 0); assert.equal(route.typeMismatches, 0); assert.equal(route.fieldPresenceMismatches, 0); }
const adapter = new StringRouteObservationAdapter(); const local = adapter.reconstruct({ normalizedLegacyRows: rows, observationSnapshot: snapshot, graph, routeVariant: 'local-strings', rootTemplate: legacyResponses['local-strings'] }); const dashboard = adapter.reconstruct({ normalizedLegacyRows: rows, observationSnapshot: snapshot, graph, routeVariant: 'strings-dashboard', rootTemplate: legacyResponses['strings-dashboard'] }); const first = local.rows[0]; assert.equal(first.stringKey, 'ST:BHE0020:A1:S1'); assert.equal(snapshot.currentStates[0].canonicalKey, binding.bindingsByDomain['string-telemetry'][0].canonicalKey); assert.equal(first.location, 'R1-Rack1'); assert.equal(first.outRotation, false); assert.equal(first.maxCellTemp, 30); assert.equal(first.measuredVoltage, 1001); assert.equal(first.ctCurrent1, null); assert.equal(Object.prototype.hasOwnProperty.call(first, 'ctCurrent2'), true); assert.equal(first.ctCurrent2, null); assert.equal(Object.prototype.hasOwnProperty.call(dashboard.rows[0], 'optionalUndefined'), true); assert.equal(dashboard.rows[0].optionalUndefined, undefined);
const mapped = adapter.reconstruct({ normalizedLegacyRows: rows, observationSnapshot: snapshot, graph, controllerIpMappings: [{ arrayIndex: 1, stringIndex: 1, ip: '10.9.9.9', source: 'legacy-ip-map' }], routeVariant: 'strings-dashboard', rootTemplate: legacyResponses['strings-dashboard'] }); assert.equal(mapped.rows[0].stringControllerIp, '10.9.9.9'); assert.equal(mapped.controllerIpSources['A1-S1'], 'legacy-ip-map'); assert.equal(mapped.controllerIpSources['A1-S2'], 'normalized-source');
const missingIpRows = rows.map((row, index) => index ? row : Object.fromEntries(Object.entries(row).filter(([key]) => !['ipAddress', 'stringControllerIp'].includes(key)))); const missingBinding = await new TelemetryBindingResolver().build({ graph, graphFingerprint: 'graph', graphSourceFingerprint: 'source', graphHealthy: true, graphCycleId: 92, profileIdentity: null, telemetryProfileIdentity: null, cycleId: 92, capturedAt: null, strings: missingIpRows, controllerHealth: null, authorities: { 'string-telemetry': { chosenProviderId: 'turtle', stale: false } }, providerHealth: { turtle: {} } }); const missingSnapshot = new ObservationResolver().build(missingBinding); const missing = adapter.reconstruct({ normalizedLegacyRows: missingIpRows, observationSnapshot: missingSnapshot, graph, routeVariant: 'strings-dashboard', rootTemplate: { strings: missingIpRows } }); assert.equal(missing.controllerIpSources['A1-S1'], 'unavailable');
const registry = createStringRouteFieldAdapterRegistry(localRows, 'local-strings'); for (const field of Object.keys(localRows[0])) assert.ok(registry.some((entry) => entry.outputField === field), `registry missing ${field}`);
const parity = new StringRouteObservationParity(); const alteredValue = structuredClone(local.response) as any; alteredValue.data[0].measuredVoltage = 9; assert.equal(parity.compare('local-strings', legacyResponses['local-strings'], alteredValue).mismatchHistogram.measuredVoltage, 1); const alteredType = structuredClone(local.response) as any; alteredType.data[0].soc = '51'; assert.equal(parity.compare('local-strings', legacyResponses['local-strings'], alteredType).typeMismatches, 1); const missingKey = structuredClone(local.response) as any; delete missingKey.data[0].soc; assert.equal(parity.compare('local-strings', legacyResponses['local-strings'], missingKey).fieldPresenceMismatches, 1); const duplicate = structuredClone(local.response) as any; duplicate.data.push(duplicate.data[0]); assert.equal(parity.compare('local-strings', legacyResponses['local-strings'], duplicate).duplicates.reconstructed, 1);
assert.deepEqual(rows, sourceBefore); assert.deepEqual(snapshot, observationBefore); assert.deepEqual(graph, graphBefore); assert.equal(Object.isFrozen(snapshot), true);
console.log('String route observation adapter tests passed');
