import React,{useState} from 'react';
import {emptyDetails,issueCategories,type IssueCategory,type FleetArray,type Quality} from '../core/fleet/details';
import {fleetMetrics,type MetricKey,type SiteView} from '../core/fleet/model';

export const value=(n:number|null,digits=1)=>n===null?'—':n.toLocaleString(undefined,{maximumFractionDigits:digits});
const time=(stamp:string|null)=>stamp?new Date(stamp).toLocaleTimeString():'Not reported';
const stateLabels={current:'Current',stale:'Stale readings',unavailable:'Collector unavailable','identity-conflict':'Identity conflict'};
const siteMetrics:MetricKey[]=['powerKw','targetKw','reactiveKvar','socPct','chargeKw','dischargeKw'];
function QualityTag({quality,stamp}:{quality:Quality;stamp?:string|null}){
  return <span className={'quality-tag '+quality} title={stamp?`Observed ${time(stamp)}`:undefined}>{quality==='live'?'Current':quality==='stale'?'Last known':'Unknown'}</span>;
}
function Symbol({kind}:{kind:'station'|'battery'|'inverter'}){
  return <svg viewBox="0 0 40 40" aria-hidden="true" className="line-symbol" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
    {kind==='station'?<><path d="M16 5h8l9 31H7L16 5Zm-5 12h18M8 25h24M13 9h14M11 35l17-18M29 35L12 17M20 5V2"/></>:kind==='battery'?<><rect x="10" y="7" width="20" height="29" rx="2"/><path d="M16 7V3h8v4M14 13h12M14 19h12M14 25h12M14 31h12"/></>:<><rect x="5" y="5" width="30" height="30" rx="2"/><path d="m6 34 28-28M10 12h8M10 16h8M23 27c4-6 4 6 8 0M23 31c4-6 4 6 8 0"/></>}
  </svg>;
}
function Branch({array,selected,onSelect}:{array:FleetArray;selected:boolean;onSelect:()=>void}){
  return <button className={'line-branch '+(selected?'selected':'')} onClick={onSelect} aria-pressed={selected} aria-label={`Review Array ${array.number}`}>
    <span className="branch-stem"/><span className="branch-title">Array {array.number}</span>
    <span className="branch-equipment"><Symbol kind="inverter"/><span className="branch-link"/><Symbol kind="battery"/></span>
    <strong>{value(array.powerKw)} <small>kW</small></strong><span className="branch-state">{array.pcsState}</span>
    <span className={'rotation '+(array.rotation==='OUT'?'out':'')}>{array.rotation==='UNKNOWN'?'Rotation unknown':`Rotation ${array.rotation.toLowerCase()}`}</span>
    <QualityTag quality={array.pcsQuality} stamp={array.pcsObservedAt}/>
  </button>;
}
export function SiteOverview({site,onFocus,focused}:{site:SiteView;onFocus:()=>void;focused:boolean}){
  const details=site.details ?? emptyDetails();
  const [arrayId,setArrayId]=useState<number|null>(null),[category,setCategory]=useState<IssueCategory|null>(null);
  const selected=details.arrays.some(a=>a.number===arrayId)?arrayId:null;
  const arrays=details.arrays.filter(a=>selected===null || a.number===selected);
  const findings=details.issues.findings.filter(f=>category===null || f.category===category);
  const temp=(n:number|null,delta=false)=>value(n===null?null:n*1.8+(delta?0:32));
  const issueUnknown=details.issues.quality==='unknown';
  return <section className="site-overview" aria-label={`${site.name} overview`}>
    <div className="site-heading"><div className="site-name"><span className="site-monogram"><Symbol kind="station"/></span><div><p className="eyebrow">{site.stationCode} / BLOCK {site.blockIndex}</p><h2>{site.name}</h2><span className="site-observed">Snapshot {time(site.observedAt)}</span></div></div><div className="site-heading-actions"><span className={'status-pill '+(site.status==='current'?'live':'stale')}>{stateLabels[site.status]}</span>{!focused && <button onClick={onFocus}>Focus site ↗</button>}</div></div>
    <div className="site-metrics">{siteMetrics.map(key=><div key={key}><span>{key==='socPct'?'Block SOC':fleetMetrics[key].label}</span><strong>{value(site.metrics[key].value)} <small>{fleetMetrics[key].unit}</small></strong><QualityTag quality={site.metrics[key].quality} stamp={site.metrics[key].observedAt}/></div>)}</div>
    <div className="site-health">
      <div className="health-total"><span className="section-kicker">Site notification targets</span><div className="alarm-totals">{(['alarms','warnings'] as const).map(key=><div key={key} className={key}><strong>{value(site.metrics[key].value,0)}</strong><span>{key==='alarms'?'Alarm':'Warning'} targets</span><QualityTag quality={site.metrics[key].quality}/></div>)}</div><p>Reported site totals. A target may have both severities.</p></div>
      <div className="sensor-summary"><div className="section-kicker">Safety sensor status <QualityTag quality={details.sensors.quality} stamp={details.sensors.observedAt}/></div><strong className={details.sensors.trips?'alarm-text':''}>{value(details.sensors.trips,0)} <small>reported trips</small></strong><p>Heat · Gas · Smoke · Fire suppression</p><span className="coverage-text">{details.sensors.known} / {details.sensors.total} reported sensor states known{details.sensors.total>details.sensors.known?' · Partial coverage':''}</span><span className="sensor-time">Snapshot report {time(details.sensors.observedAt)}</span></div>
      <div className="site-capacity"><span className="section-kicker">Installed system</span><strong>{value(site.metrics.capacityKwh.value===null?null:site.metrics.capacityKwh.value/1000,2)} <small>MWh</small></strong><p>{value(site.metrics.strings.value,0)} strings · {details.arrays.length || '—'} reported arrays</p><QualityTag quality={site.metrics.capacityKwh.quality}/><span className="coverage-text">Stored energy: {value(site.metrics.storedKwh.value)} kWh</span></div>
    </div>
    {details.sensors.active.length>0 && <div className="sensor-fault-panel"><div className="subheading"><h3>Reported sensor conditions</h3><QualityTag quality={details.sensors.quality} stamp={details.sensors.observedAt}/></div><div className="table-wrap"><table className="sensor-fault-table"><thead><tr><th>Affected enclosure / sensor</th><th>Reported condition</th><th>System findings / source</th><th>Trip timestamp</th></tr></thead><tbody>{details.sensors.active.map(trip=><tr key={trip.id}><th>{trip.label}<span className="row-meta">{trip.kind}</span></th><td><span className={'severity '+(!trip.condition || trip.condition==='trip'?'alarm':'warning')}>{trip.condition==='communication'?'Communication':trip.condition==='temperature'?'High temperature':trip.condition==='reported-status'?'Reported status':'Physical trip'}</span><strong>{trip.status || 'Detailed status not supplied'}</strong><span className="row-meta">{trip.message || 'Collector reported a trip without a detailed condition.'}</span></td><td>{trip.findings?.length?trip.findings.map((finding,index)=><div key={index}>{finding}</div>):<span>No additional system finding supplied.</span>}<span className="row-meta">{trip.source || 'Source not supplied'}</span>{trip.sourcePath && <span className="row-meta sensor-source-path">{trip.sourcePath}</span>}</td><td>{trip.occurredAt?new Date(trip.occurredAt).toLocaleString():'Not supplied'}<span className="row-meta">Snapshot {time(details.sensors.observedAt)}</span></td></tr>)}</tbody></table></div>{details.sensors.omittedTrips>0 && <p className="source-note">{details.sensors.omittedTrips} additional sensor conditions not included in this overview.</p>}</div>}
    <div className="panel-section"><div className="subheading"><div><h3>Site one-line</h3><p>Select an array to inspect its readings. Select the station to show all arrays.</p></div><span className="diagram-note">Topology schematic · Not switch-position telemetry</span></div>
      {details.arrays.length?<div className="one-line"><button className="station-node" onClick={()=>setArrayId(null)} aria-label={`Show all arrays for ${site.name}`}><Symbol kind="station"/><span><strong>{site.stationCode}</strong><small>Site connection · {value(site.metrics.powerKw.value)} kW</small></span><span className="show-all">All arrays</span></button><div className="site-trunk"/><div className="array-branches" style={{gridTemplateColumns:`repeat(${details.arrays.length}, minmax(112px, 1fr))`}}>{details.arrays.map(array=><Branch key={array.number} array={array} selected={selected===array.number} onSelect={()=>setArrayId(selected===array.number?null:array.number)}/>)}</div></div>:<p className="empty-state">Array topology has not been supplied by this collector.</p>}
    </div>
    <div className="panel-section array-section"><div className="subheading"><div><h3>{selected?`Array ${selected} readings`:'Array operating detail'}</h3><p>Array-wide extremes · Average of reporting string averages · Collection segments excluded</p></div><div className="compact-controls">{selected && <button onClick={()=>setArrayId(null)}>Show all arrays</button>}<span className="temperature-unit">Temperatures in °F</span></div></div>
      <div className="table-wrap"><table className="array-table"><thead><tr><th rowSpan={2}>Array / coverage</th><th rowSpan={2}>Online strings<br/>Out of rotation</th><th rowSpan={2}>Online SOC<br/>Bus voltage</th><th colSpan={4} className="temperature-heading">Cell temperature · °F</th><th colSpan={4} className="voltage-heading">Cell voltage · mV</th></tr><tr>{['Min','Average','Max','Δ'].map(s=><th key={'t'+s} className="temperature-heading">{s}</th>)}{['Min','Average','Max','Δ'].map(s=><th key={'v'+s} className="voltage-heading">{s}</th>)}</tr></thead><tbody>{arrays.map(array=><tr key={array.number} className={selected===array.number?'selected-row':''}><th><button className="text-button" onClick={()=>setArrayId(selected===array.number?null:array.number)}>Array {array.number}</button><span className="row-meta"><QualityTag quality={array.quality} stamp={array.observedAt}/> · {time(array.observedAt)}</span><span className="row-meta">T {array.temperatureC.reportingStrings}/{array.temperatureC.expectedStrings} · V {array.voltageMv.reportingStrings}/{array.voltageMv.expectedStrings} strings{array.temperatureC.partial || array.voltageMv.partial?' · partial':''}</span></th><td>{value(array.onlineStrings,0)} / {value(array.stringCount,0)}<span className="row-meta">{value(array.outOfRotation,0)} out</span></td><td>{value(array.socPct)}%<span className="row-meta">{value(array.busVoltage)} V</span></td><td>{temp(array.temperatureC.minimum)}</td><td className="average-cell">{temp(array.temperatureC.average)}</td><td>{temp(array.temperatureC.maximum)}</td><td className="delta-cell">{temp(array.temperatureC.delta,true)}</td><td>{value(array.voltageMv.minimum)}</td><td className="average-cell">{value(array.voltageMv.average)}</td><td>{value(array.voltageMv.maximum)}</td><td className="delta-cell">{value(array.voltageMv.delta)}</td></tr>)}</tbody></table></div>
      {!arrays.length && <p className="empty-state">No array readings available. Missing values are not zero.</p>}{details.omittedArrays>0 && <p className="fine">{details.omittedArrays} additional arrays omitted from this bounded overview.</p>}
    </div>
    <div className="panel-section issues-section"><div className="subheading"><div><h3>Issues & availability</h3><p>Unique affected targets by category. Categories and severities overlap; do not add these counts.</p></div><QualityTag quality={details.issues.quality} stamp={details.issues.observedAt}/></div>
      <div className="issue-categories">{(Object.keys(issueCategories) as IssueCategory[]).map(key=>{const counts=details.issues.categories[key];return <button key={key} aria-pressed={category===key} className={category===key?'selected':''} onClick={()=>setCategory(category===key?null:key)}><span>{issueCategories[key]}</span><strong>{value(counts.targets,0)} <small>targets</small></strong><span className="issue-breakdown"><span className={counts.alarms?'alarm-text':''}>{value(counts.alarms,0)} alarm</span><span className={counts.warnings?'warning-text':''}>{value(counts.warnings,0)} warning</span></span><span className="row-meta">{value(counts.info,0)} info · {value(counts.unknown,0)} unclassified</span></button>;})}</div>
      <div className="finding-heading"><span>{category?issueCategories[category]:'All categories'} · {findings.length} displayed groups</span>{category && <button className="text-button" onClick={()=>setCategory(null)}>Clear filter</button>}<span>Reported {time(details.issues.observedAt)}</span></div>
      {findings.length>0?<div className="table-wrap"><table className="findings-table"><thead><tr><th>Severity / code</th><th>Notification</th><th>Affected targets</th></tr></thead><tbody>{findings.map((finding,index)=><tr key={`${finding.category}:${finding.code}:${index}`}><td><span className={'severity '+finding.severity}>{finding.severity}</span><span className="row-meta">{finding.code || 'No code'}</span></td><td><strong>{finding.title}</strong><span className="row-meta">{issueCategories[finding.category]}</span></td><td>{finding.targets.join(' · ') || 'Target details unavailable'}{finding.targetCount>finding.targets.length && <span className="row-meta">+{finding.targetCount-finding.targets.length} additional targets</span>}</td></tr>)}</tbody></table></div>:<p className="empty-state">{issueUnknown?'Detailed issue coverage is unavailable from this collector.':'No notification groups reported for this selection.'}</p>}
      {details.issues.notes.map((note,index)=><p className="source-note" key={index}>{note}</p>)}{details.issues.omittedGroups>0 && <p className="source-note">{details.issues.omittedGroups} additional notification groups are not included in this overview.</p>}
    </div>
  </section>;
}
