import assert from "node:assert/strict";
import { qualifyPcsProcessPoint, pcsSourceLabel, mergePcsReading } from "./pcsDataQuality";
import { pcsNumber, formatPcsProcessReading } from "../../lib/pcsReading";
const now = Date.parse("2026-09-23T21:00:00Z");
for (const value of [null, undefined, "", " ", false, true, NaN, Infinity, "--", {}, []]) assert.equal(pcsNumber(value), null);
assert.equal(pcsNumber(0), 0);
assert.equal(pcsNumber("-1.5"), -1.5);
const point = {value: 0, quality: 0, timestamp: now / 1000};
assert.equal(formatPcsProcessReading(qualifyPcsProcessPoint(point, now), "A"), "0.0 A");
assert.equal(qualifyPcsProcessPoint({...point, timestamp: now}, now).readingState, "live");
for (const value of [null, "", false]) assert.equal(formatPcsProcessReading(qualifyPcsProcessPoint({...point, value}, now)), "Not reported");
for (const quality of [null, undefined, 1, 2]) assert.equal(qualifyPcsProcessPoint({...point, quality}, now).readingState, "unavailable");
for (const timestamp of [null, 0, "", (now + 60_000) / 1000]) assert.equal(qualifyPcsProcessPoint({...point, timestamp}, now).readingState, "unverified");
assert.equal(qualifyPcsProcessPoint(point, now + 120_001).readingState, "stale");
assert.match(formatPcsProcessReading(qualifyPcsProcessPoint({...point, value: 45}, now + 180_000), "°C"), /45.0 °C · stale \(180s\)/);
assert.equal(point.timestamp, now / 1000, "publication must not renew source timestamp");
assert.match(formatPcsProcessReading({value: 0}), /freshness unknown/);
const configuration = {value:3960,quality:null,timestamp:null,isConfiguration:true,receivedAt:now};
assert.equal(qualifyPcsProcessPoint(configuration,now).readingState,"live");
assert.equal(qualifyPcsProcessPoint(configuration,now+120_001).readingState,"stale");
assert.equal(qualifyPcsProcessPoint({...configuration,quality:2},now).readingState,"unavailable");
assert.equal(qualifyPcsProcessPoint({...configuration,isConfiguration:false},now).readingState,"unavailable");
assert.equal(qualifyPcsProcessPoint({...point,id:4853,timestamp:(now-30*86400_000)/1000,receivedAt:now},now).readingState,"live");
assert.equal(pcsSourceLabel(true, "SMA_WEB_PROCESS_DATA", true), "EMS Modbus + SMA HTTP");
assert.equal(pcsSourceLabel(false, "SMA_MODBUS", true), "direct PCS Modbus");
assert.equal(pcsSourceLabel(true, "SMA_WEB_PROCESS_DATA", false), "EMS Modbus");
console.log("PCS missing values, per-point freshness, source identity and display tests passed");
let rows: {arrayIndex: number; capturedAt: number; stale: boolean}[] = [];
for (const arrayIndex of [8, 3, 7, 1, 4, 2, 6, 5]) {
  const previous = rows;
  rows = mergePcsReading(rows, {arrayIndex, capturedAt: now, stale: false});
  assert.equal(rows.length, previous.length + 1);
  assert.ok(rows.every(Boolean), 'Partially completed PCS batches must not contain holes or undefined.');
}
assert.deepEqual(rows.map(row => row.arrayIndex), [1,2,3,4,5,6,7,8]);
const refreshed = mergePcsReading(rows, {arrayIndex:3, capturedAt:now + 1, stale:true});
assert.equal(refreshed.length, 8);
assert.equal(refreshed[2].capturedAt, now + 1);
assert.equal(refreshed[2].stale, true, 'Merging must preserve source quality.');
assert.equal(rows[2].capturedAt, now, 'Published revisions must not be mutated.');
const sparse = new Array<typeof rows[number]>(5);
sparse[4] = rows[4];
assert.deepEqual(mergePcsReading([...sparse, null], rows[0]).map(row=>row.arrayIndex), [1,5]);
console.log('PCS out-of-order completion: dense partial batches, identity replacement, immutable revisions and sparse recovery passed.');
