import { coordinatorProfiler } from '../profiler';
import { deeplyImmutable } from '../../workspaceProjections/ProjectionHelpers';
import { collectTelemetrySnapshot } from '../TelemetryRuntime';
import { getLatestTopologySourceSnapshot, getTopologyGraphHealth, requestTopologyGraphRebuild } from '../../topology/TopologyGraphRuntime';
import { telemetryBindingRuntime } from '../binding';
import { observationRuntime } from '../../observations';
import { workspaceProjectionRuntime } from '../../workspaceProjections/WorkspaceProjectionRuntime';
import { CanonicalPublicationMetrics } from './CanonicalPublicationMetrics';
import type { CanonicalPublicationState, CanonicalPublicationStatus, CanonicalStageName, CanonicalStageStatus } from './CanonicalPublicationTypes';

export type CanonicalStageExecutor = (cycleId: number) => Promise<Omit<CanonicalStageStatus, 'stage' | 'evaluatedCycleId' | 'durationMs'>>;
export interface CanonicalPublicationStages { readonly topology: CanonicalStageExecutor; readonly telemetry: CanonicalStageExecutor; readonly binding: CanonicalStageExecutor; readonly observation: CanonicalStageExecutor; readonly projection: CanonicalStageExecutor }
const outcome = (state: CanonicalStageStatus['state'], producingCycleId: number | null, fingerprint: string | null, extras: Partial<CanonicalStageStatus> = {}) => ({ state, producingCycleId, failureCycleId: null, skippedUnchanged: false, retainedLastKnownGood: false, fingerprint, sourceFingerprint: null, profileIdentity: null, error: null, ...extras });

const defaultStages: CanonicalPublicationStages = {
  topology: async (cycleId) => { const before = getLatestTopologySourceSnapshot(); const result = await requestTopologyGraphRebuild('coordinator:canonical-publication', false); const source = getLatestTopologySourceSnapshot(); const health = getTopologyGraphHealth(); const ready = ['READY_HYBRID', 'READY_GRAPH'].includes(health.state) && !result.retainedLastKnownGood; return outcome(ready ? 'READY' : 'DEGRADED', source?.cycleId ?? null, result.graphFingerprint, { failureCycleId: ready ? null : cycleId, sourceFingerprint: result.sourceFingerprint, profileIdentity: source?.profileIdentity.connectionProfileId ?? null, skippedUnchanged: !result.rebuilt && !result.retainedLastKnownGood && before?.fingerprint === result.sourceFingerprint, retainedLastKnownGood: result.retainedLastKnownGood, error: ready ? null : health.lastError ?? 'topology-not-ready' }); },
  telemetry: async (cycleId) => { const snapshot = await collectTelemetrySnapshot(); const stale = Object.values(snapshot.authorities).some((value: any) => value?.stale); const aligned = snapshot.cycleId === cycleId; const ready = !stale && aligned; return outcome(ready ? 'READY' : 'DEGRADED', snapshot.cycleId, null, { failureCycleId: ready ? null : cycleId, retainedLastKnownGood: stale, error: !aligned ? `telemetry-cycle-mismatch:${snapshot.cycleId}:${cycleId}` : stale ? 'telemetry-stale-authority' : null }); },
  binding: async (cycleId) => { const before = telemetryBindingRuntime.getLatestBindingSnapshot(); const snapshot = await telemetryBindingRuntime.requestRebuild('coordinator:canonical-publication', false); const health = telemetryBindingRuntime.getLatestBindingHealth(); const ready = health.runtimeState === 'READY'; return outcome(ready ? 'READY' : 'DEGRADED', snapshot.cycleId, snapshot.bindingFingerprint, { failureCycleId: ready ? null : cycleId, sourceFingerprint: snapshot.graphSourceFingerprint, skippedUnchanged: before?.bindingFingerprint === snapshot.bindingFingerprint && before?.generatedAt === snapshot.generatedAt, retainedLastKnownGood: !ready, error: ready ? null : String(health.lastError ?? 'binding-not-ready') }); },
  observation: async (cycleId) => { const before = observationRuntime.getLatestObservationSnapshot(); const snapshot = await observationRuntime.requestObservationRebuild('coordinator:canonical-publication', false); const health = observationRuntime.getLatestObservationHealth(); const ready = health.runtimeState === 'READY'; return outcome(ready ? 'READY' : 'DEGRADED', snapshot.cycleId, snapshot.observationFingerprint, { failureCycleId: ready ? null : cycleId, sourceFingerprint: snapshot.bindingFingerprint, skippedUnchanged: before?.observationFingerprint === snapshot.observationFingerprint && before?.generatedAt === snapshot.generatedAt, retainedLastKnownGood: !ready, error: ready ? null : String(health.lastError ?? 'observation-not-ready') }); },
  projection: async (cycleId) => { const before = workspaceProjectionRuntime.report(); const snapshots = await workspaceProjectionRuntime.requestBuild(false); const after = workspaceProjectionRuntime.report(); const envelope = snapshots.operator; const ready = envelope.health === 'healthy' && !envelope.retainedLastKnownGood; return outcome(ready ? 'READY' : 'DEGRADED', envelope.producingCycleId, envelope.observationFingerprint, { failureCycleId: ready ? null : cycleId, sourceFingerprint: envelope.bindingFingerprint, skippedUnchanged: before.inputKey === after.inputKey, retainedLastKnownGood: envelope.retainedLastKnownGood, error: ready ? null : 'workspace-projection-degraded' }); },
};
const names: readonly CanonicalStageName[] = ['topology', 'telemetry', 'binding', 'observation', 'projection', 'validation', 'publish'];
const empty = (): CanonicalPublicationStatus => deeplyImmutable({ publicationCycleId: null, startedAt: null, completedAt: null, durationMs: null, state: 'UNINITIALIZED', activeStage: null, stages: Object.fromEntries(names.map((name) => [name, null])) as Record<CanonicalStageName, null>, producingCycleIds: Object.fromEntries(names.map((name) => [name, null])) as Record<CanonicalStageName, null>, fingerprints: { graph: null, graphSource: null, binding: null, observation: null }, retainedLastKnownGoodStages: [], degradedStages: [], failedStages: [], errors: [], profileIdentity: null, cycleAligned: false, freshStartInitialized: false });

export class CanonicalPublicationRuntime {
  private latest: CanonicalPublicationStatus = empty(); private history: CanonicalPublicationStatus[] = []; private inFlight: Promise<CanonicalPublicationStatus> | null = null; readonly metrics = new CanonicalPublicationMetrics();
  constructor(private readonly stages: CanonicalPublicationStages = defaultStages, private readonly historyLimit = 20) {}
  publish(cycleId: number): Promise<CanonicalPublicationStatus> { if (this.inFlight) return this.inFlight; this.inFlight = this.execute(cycleId).finally(() => { this.inFlight = null; }); return this.inFlight; }
  status() { return deeplyImmutable(structuredClone(this.latest)); }
  report() { return deeplyImmutable({ latest: structuredClone(this.latest), history: structuredClone(this.history), metrics: this.metrics.report() }); }
  private async execute(cycleId: number) { const started = performance.now(); const startedAt = new Date().toISOString(); const previous = this.latest; const stageValues = Object.fromEntries(names.map((name) => [name, null])) as Record<CanonicalStageName, CanonicalStageStatus | null>; this.latest = deeplyImmutable({ ...empty(), publicationCycleId: cycleId, startedAt, state: 'PUBLISHING', activeStage: 'topology' });
    const publication = await coordinatorProfiler.withPhase('canonical-publication', { waitState: 'NORMALIZATION', blocking: true }, async () => {
      let blocked = false;
      for (const name of ['topology', 'telemetry', 'binding', 'observation', 'projection'] as const) { if (blocked && name !== 'telemetry') { stageValues[name] = this.blocked(name, cycleId, previous, stageValues, `dependency-blocked:${name}`); continue; } this.latest = deeplyImmutable({ ...this.latest, activeStage: name }); const stage = await this.evaluate(name, cycleId, previous.stages[name]); stageValues[name] = stage; if ((name === 'topology' || name === 'telemetry' || name === 'binding' || name === 'observation') && stage.state !== 'READY') blocked = true; }
      stageValues.validation = coordinatorProfiler.withSyncPhase('validation', { waitState: 'NORMALIZATION', blocking: true }, () => this.validate(cycleId, stageValues));
      stageValues.publish = coordinatorProfiler.withSyncPhase('publish', { waitState: 'NORMALIZATION', blocking: true }, () => ({ ...outcome(stageValues.validation!.state, cycleId, stageValues.observation?.fingerprint ?? null, { failureCycleId: stageValues.validation!.failureCycleId, error: stageValues.validation!.error }), stage: 'publish' as const, evaluatedCycleId: cycleId, durationMs: 0 }));
      return stageValues;
    });
    const values = Object.values(publication).filter((value): value is CanonicalStageStatus => value != null); const failed = values.filter((value) => value.state === 'FAILED').map((value) => value.stage); const degraded = values.filter((value) => value.state === 'DEGRADED' || value.state === 'BLOCKED').map((value) => value.stage); const retained = values.filter((value) => value.retainedLastKnownGood).map((value) => value.stage); const errors = values.map((value) => value.error).filter((value): value is string => !!value); const validation = publication.validation!; const state: CanonicalPublicationState = failed.length ? 'FAILED' : degraded.length || validation.state !== 'READY' ? 'DEGRADED' : 'READY'; const status: CanonicalPublicationStatus = deeplyImmutable({ publicationCycleId: cycleId, startedAt, completedAt: new Date().toISOString(), durationMs: performance.now() - started, state, activeStage: null, stages: publication, producingCycleIds: Object.fromEntries(names.map((name) => [name, publication[name]?.producingCycleId ?? null])) as Record<CanonicalStageName, number | null>, fingerprints: { graph: publication.topology?.fingerprint ?? null, graphSource: publication.topology?.sourceFingerprint ?? null, binding: publication.binding?.fingerprint ?? null, observation: publication.observation?.fingerprint ?? null }, retainedLastKnownGoodStages: retained, degradedStages: degraded, failedStages: failed, errors, profileIdentity: publication.topology?.profileIdentity ?? null, cycleAligned: validation.state === 'READY', freshStartInitialized: ['topology', 'binding', 'observation', 'projection'].every((name) => publication[name as CanonicalStageName]?.producingCycleId != null) }); this.latest = status; this.history.push(status); if (this.history.length > this.historyLimit) this.history.shift(); this.metrics.record(status); return status;
  }
  private async evaluate(name: keyof CanonicalPublicationStages, cycleId: number, previous: CanonicalStageStatus | null): Promise<CanonicalStageStatus> { const started = performance.now(); try { const value = await coordinatorProfiler.withPhase(name === 'observation' ? 'observations' : name === 'projection' ? 'workspace-projections' : name === 'topology' ? 'topology-graph' : name === 'telemetry' ? 'telemetry-runtime' : 'telemetry-binding', { waitState: 'NORMALIZATION', blocking: true }, () => this.stages[name](cycleId)); return deeplyImmutable({ ...value, stage: name, evaluatedCycleId: cycleId, durationMs: performance.now() - started }); } catch (error) { return deeplyImmutable({ stage: name, state: 'FAILED', evaluatedCycleId: cycleId, producingCycleId: previous?.producingCycleId ?? null, failureCycleId: cycleId, durationMs: performance.now() - started, skippedUnchanged: false, retainedLastKnownGood: previous?.producingCycleId != null, fingerprint: previous?.fingerprint ?? null, sourceFingerprint: previous?.sourceFingerprint ?? null, profileIdentity: previous?.profileIdentity ?? null, error: error instanceof Error ? error.message : String(error) }); } }
  private blocked(name: CanonicalStageName, cycleId: number, previousStatus: CanonicalPublicationStatus, values: Record<CanonicalStageName, CanonicalStageStatus | null>, error: string): CanonicalStageStatus { const previous = previousStatus.stages[name]; return deeplyImmutable({ stage: name, state: 'BLOCKED', evaluatedCycleId: cycleId, producingCycleId: previous?.producingCycleId ?? null, failureCycleId: cycleId, durationMs: 0, skippedUnchanged: false, retainedLastKnownGood: previous?.producingCycleId != null, fingerprint: previous?.fingerprint ?? null, sourceFingerprint: previous?.sourceFingerprint ?? null, profileIdentity: previous?.profileIdentity ?? values.topology?.profileIdentity ?? null, error }); }
  private validate(cycleId: number, values: Record<CanonicalStageName, CanonicalStageStatus | null>): CanonicalStageStatus { const topology = values.topology; const telemetry = values.telemetry; const binding = values.binding; const observation = values.observation; const projection = values.projection; const errors: string[] = []; if (telemetry?.producingCycleId !== cycleId) errors.push('telemetry-cycle-misaligned'); if (binding?.producingCycleId !== cycleId) errors.push('binding-cycle-misaligned'); if (observation?.producingCycleId !== cycleId) errors.push('observation-cycle-misaligned'); if (projection?.producingCycleId !== cycleId) errors.push('projection-cycle-misaligned'); if (binding?.sourceFingerprint !== topology?.sourceFingerprint) errors.push('graph-source-fingerprint-misaligned'); if (observation?.sourceFingerprint !== binding?.fingerprint) errors.push('binding-fingerprint-misaligned'); if (projection?.fingerprint !== observation?.fingerprint) errors.push('observation-fingerprint-misaligned'); return deeplyImmutable({ stage: 'validation', state: errors.length ? 'DEGRADED' : 'READY', evaluatedCycleId: cycleId, producingCycleId: cycleId, failureCycleId: errors.length ? cycleId : null, durationMs: 0, skippedUnchanged: false, retainedLastKnownGood: false, fingerprint: projection?.fingerprint ?? null, sourceFingerprint: topology?.sourceFingerprint ?? null, profileIdentity: topology?.profileIdentity ?? null, error: errors.length ? errors.join(',') : null }); }
}
export const canonicalPublicationRuntime = new CanonicalPublicationRuntime();
