// Isolated UI + real thermal route acceptance test. Never starts the coordinator.
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createRequire} from "node:module";
import express from "express";
import {build} from "esbuild";
import {thermalService} from "./thermalService";
import {thermalRouter} from "./thermalRoutes";

// Use an existing local Playwright installation; no download or device access.
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PRIZM_PLAYWRIGHT_PATH || "@playwright/test");
const directory=await fs.mkdtemp(path.join(os.tmpdir(),"prizm-thermal-browser-"));
process.env.PRIZM_THERMAL_DIR=directory;
const now=Date.now();
const fixtureSite={id:"fixture-only-site",label:"Fixture Site"};
const devices=Array.from({length:5},(_,i)=>({ip:`10.0.1.${i+1}`,arrayIndex:i===4?2:1,segmentLabel:`ES${i+1}`,
  lastSuccessUtc:new Date(now-(i===3?180000:0)).toISOString(),spaceTemperatureC:20+i*3,avgCellTemperatureC:24+i,
  controlTemperatureC:26+i,outsideTemperatureC:15,supplyAirTempC:12,spaceHumidityPct:35,
  hvac1:{currentA:i===2?undefined:i*2,compressorOn:true,reversingValveOn:false},hvac2:{currentA:0,compressorOn:false,electricHeatOn:false},
  faultMessages:i===1?["Fixture fault"]:[]}));
thermalService().ingest(devices,now,fixtureSite);await thermalService().flush();
await build({stdin:{contents:'import React from "react"; import {createRoot} from "react-dom/client"; import Workspace from "./src/components/ThermalWorkspace"; createRoot(document.getElementById("root")).render(<Workspace/>);',loader:"tsx",resolveDir:process.cwd()},bundle:true,format:"esm",outfile:path.join(directory,"app.js"),plugins:[{name:"isolated-refresh",setup(b){b.onResolve({filter:/SiteDataContext$/},()=>({path:"refresh",namespace:"test"}));b.onLoad({filter:/.*/,namespace:"test"},()=>({contents:'export const useSiteData=()=>({lastUpdated:"fixture"});'}));}}]});
const assets=await fs.readdir("dist/assets");
const css=assets.find(name=>name.startsWith("index-")&&name.endsWith(".css"));
const app=express();app.use(express.json());app.use("/api/local/site-data/thermal",thermalRouter);
app.get("/",(_req,res)=>res.send(`<html><head><link rel="stylesheet" href="/style.css"></head><body><div id="root"></div><script type="module" src="/app.js"></script></body></html>`));
app.get("/style.css",(_req,res)=>res.sendFile(path.resolve("dist/assets",css!)));app.use(express.static(directory));
const server=app.listen(0,"127.0.0.1");await new Promise<void>(resolve=>server.once("listening",resolve));
const address=server.address();assert(address&&typeof address!=="string");const url=`http://127.0.0.1:${address.port}`;
const browser=await chromium.launch({headless:true});
try {
 const page=await browser.newPage({viewport:{width:1366,height:900}});const requests:string[]=[];const errors:string[]=[];
 page.on("request",request=>{if(request.url().includes("/api/")){if(request.method()!=="GET")assert(request.method()==="POST"&&(request.url().endsWith("/thermal/storage")||request.url().endsWith("/site-history/query")),"Only explicitly tested local storage settings may be written");requests.push(request.url());}});
 page.on("pageerror",error=>errors.push(error.message));
 await page.goto(url);await page.getByRole("heading",{name:"Filtered results · 10 HVAC units",exact:true}).waitFor();
 await page.getByLabel("Map metric",{exact:true}).selectOption("current");
 await page.getByLabel("Minimum reading",{exact:true}).fill("1");
 await page.getByRole("heading",{name:"Filtered results · 2 HVAC units",exact:true}).waitFor();
 const row=page.getByRole("button",{name:"Array 1 · ES2 · HVAC 1",exact:true});await row.click();
 await page.getByRole("heading",{name:"Array 1 · ES2 · HVAC 1 · Current readings",exact:true}).waitFor();
 assert.equal(await page.getByRole("button",{name:"Toggle Array 1 · ES2",exact:true}).getAttribute("aria-pressed"),"true");
 const segment=page.getByRole("button",{name:"Toggle Array 1 · ES2",exact:true});
 assert((await segment.innerText()).includes("2.0 A"));
 assert((await segment.innerText()).includes("0.0 A"));
 await page.getByRole("checkbox",{name:"Show whole-site outlier graph",exact:true}).check();
 const overview=page.getByRole("region",{name:"Whole-site thermal overview",exact:true});
 await overview.getByText(/7 of 10 HVAC units plotted/).waitFor();
 assert.equal(await overview.getByRole("button",{name:/^Graph Array/}).count(),7,"Plot the whole site despite numeric filters");
 const outlier=overview.getByRole("button",{name:"Graph Array 2 · ES5 · HVAC 1: 8.0 A",exact:true});
 await outlier.focus();await outlier.press("Enter");
 await page.getByRole("button",{name:"Record these 4 units",exact:true}).waitFor();
 assert.equal(await page.getByRole("button",{name:"Toggle Array 2 · ES5",exact:true}).getAttribute("aria-pressed"),"true");
 await outlier.click();
 await page.getByRole("button",{name:"Record these 2 units",exact:true}).waitFor();
 const graphs=page.getByRole("region",{name:"Selected thermal graphs",exact:true});
 await graphs.locator('.recharts-legend-item-text').filter({hasText:"Array 1 · ES2 · HVAC 1"}).waitFor();
 await graphs.locator('.recharts-legend-item-text').filter({hasText:"Array 1 · ES2 · HVAC 2"}).waitFor();
 await page.getByLabel("Graph metric",{exact:true}).selectOption("cell");
 assert.equal(await page.getByLabel("Map metric",{exact:true}).inputValue(),"cell");
 assert.equal(await page.getByLabel("Minimum reading",{exact:true}).inputValue(),"");
 await page.getByLabel("Search equipment",{exact:true}).fill("no-match");
 await page.getByText("No equipment matches these filters.",{exact:true}).waitFor();
 await page.getByRole("heading",{name:"Array 1 · ES2 · HVAC 1 · Current readings",exact:true}).waitFor();
 await page.getByRole("button",{name:"Clear filters",exact:true}).click();
 await page.getByRole("button",{name:"Toggle Array 1 · ES1",exact:true}).click();
 await page.getByRole("heading",{name:"Array 1 · ES1 · HVAC 1 · Current readings",exact:true}).waitFor();
 assert.equal(await page.getByRole("button",{name:"Toggle Array 1 · ES2",exact:true}).getAttribute("aria-pressed"),"true");
 await page.getByRole("button",{name:"Record these 4 units",exact:true}).waitFor();
 // No comparison checkbox: every segment click adds/removes its complete pair.
 await page.getByRole("button",{name:"Toggle Array 1 · ES1",exact:true}).click();
 await page.getByRole("button",{name:"Record these 2 units",exact:true}).waitFor();
 await page.getByRole("button",{name:"Toggle Array 1 · ES1",exact:true}).click();
 await page.getByRole("button",{name:"Toggle Array 1 · ES3",exact:true}).click();
 await page.getByRole("button",{name:"Toggle Array 1 · ES4",exact:true}).click();
 await page.getByRole("button",{name:"Record these 8 units",exact:true}).waitFor();
 await page.getByRole("button",{name:"Toggle Array 2 · ES5",exact:true}).click();
 await page.getByRole("button",{name:"Record these 10 units",exact:true}).waitFor();
 assert.equal(await page.getByLabel("Recording to review",{exact:true}).inputValue(),"site");
 assert.equal(await page.getByRole("button",{name:"Toggle Array 2 · ES5",exact:true}).getAttribute("aria-pressed"),"true");
 await page.getByRole("button",{name:"Toggle Array 2 · ES5",exact:true}).click();
 await page.getByRole("button",{name:"Toggle Array 1 · ES3",exact:true}).click();
 await page.getByRole("button",{name:"Toggle Array 1 · ES4",exact:true}).click();

 await page.getByLabel("Reading quality",{exact:true}).selectOption("Stale");
 await page.getByRole("heading",{name:"Filtered results · 2 HVAC units",exact:true}).waitFor();
 await page.getByRole("button",{name:"Clear filters",exact:true}).click();
 await page.getByLabel("Minimum reading",{exact:true}).fill("76");
 await page.getByRole("heading",{name:"Filtered results · 6 HVAC units",exact:true}).waitFor();
 assert.equal(await page.getByLabel("Map metric",{exact:true}).locator("option:checked").innerText(),"Average cell temperature (°F)");
 assert(!(await page.locator("body").innerText()).includes("°C"),"Page must use Fahrenheit throughout");
 const history=await (await fetch(`${url}/api/local/site-data/thermal/history?ids=10.0.1.2/hvac/1&from=0`)).json();
 assert.equal(history.points[0].point.cell,25,"Recording remains canonical Celsius");
 assert.equal(history.points[0].displayValues.cell,77,"Graph values use Fahrenheit");
 await page.getByRole("button",{name:"Clear filters",exact:true}).click();
 await page.setViewportSize({width:600,height:900});
 const positions=await page.locator('[data-thermal-array="1"] [data-thermal-segment]').evaluateAll(nodes=>nodes.map(node=>({top:node.getBoundingClientRect().top,left:node.getBoundingClientRect().left})));
 assert.equal(new Set(positions.map(p=>p.top)).size,1,"All segments must stay in one row");
 assert(positions.every((p,i)=>i===0||p.left>positions[i-1].left),"Segments are laid out horizontally");
 const overflow=await page.getByLabel("Thermal overhead map",{exact:true}).evaluate(node=>node.scrollWidth>node.clientWidth);
 assert(!overflow,"Small screens must fit all segments without horizontal scrolling");
 await page.setViewportSize({width:1366,height:900});
 await page.screenshot({path:path.join(directory,"thermal-workspace.png"),fullPage:true});
 assert.equal(requests.filter(r=>r.endsWith("/thermal")).length,1,"selection and filters must not reload the snapshot");
 assert(requests.every(r=>r.includes("/api/local/site-data/thermal")),"no equipment endpoints");
 // Exercise a full-sized array, not just the four-segment selection fixture.
 thermalService().ingest([...devices,...Array.from({length:24},(_,i)=>({...devices[0],ip:`10.0.3.${i+1}`,arrayIndex:3,segmentLabel:`ES${i+1}`}))],now,fixtureSite);
 await thermalService().flush();
 await page.getByRole("button",{name:"Refresh view",exact:true}).click();
 await page.locator('[data-thermal-array="3"] [data-thermal-segment="ES24"]').waitFor();
 for(const width of [1366,1024,600]){
   await page.setViewportSize({width,height:900});
   const geometry=await page.getByLabel("Thermal overhead map",{exact:true}).evaluate(node=>{
     const bounds=node.getBoundingClientRect();
     const tiles=Array.from(node.querySelectorAll('[data-thermal-array="3"] [data-thermal-segment]') as NodeListOf<HTMLElement>).map(tile=>{const rect=tile.getBoundingClientRect();return {left:rect.left,right:rect.right,top:rect.top};});
     return {left:bounds.left,right:bounds.right,width:node.clientWidth,scrollWidth:node.scrollWidth,tiles};
   });
   assert.equal(geometry.tiles.length,24);
   assert.equal(new Set(geometry.tiles.map(tile=>tile.top)).size,1);
   assert(geometry.tiles.every(tile=>tile.left>=geometry.left&&tile.right<=geometry.right+1));
   assert(geometry.scrollWidth<=geometry.width+1,`Array must fit at ${width}px`);
 }
 await page.setViewportSize({width:1366,height:900});
 await page.screenshot({path:path.join(directory,"thermal-workspace-fit.png"),fullPage:true});
 await page.getByLabel("Map metric",{exact:true}).selectOption("current");
 await overview.getByText(/55 of 58 HVAC units plotted/).waitFor();
 await overview.getByRole("button",{name:"Show highest readings in results",exact:true}).click();
 assert.equal(await page.locator("tbody tr").first().getByRole("button").innerText(),"Array 2 · ES5 · HVAC 1");
 await page.screenshot({path:path.join(directory,"thermal-site-overview.png"),fullPage:true});
 assert.deepEqual(errors,[]);
 // Exercise actual storage APIs through the modal, using the isolated history directory.
 await page.getByRole("button",{name:"Site history storage",exact:true}).click();
 const storage=page.getByRole("dialog",{name:"Site history storage",exact:true});
 await storage.getByRole("button",{name:"Start site recording",exact:true}).waitFor();
 await storage.getByLabel("Site storage cap GiB",{exact:true}).fill("0.2");
 await storage.getByRole("button",{name:"Start site recording",exact:true}).click();
 await storage.getByText("Recording enabled",{exact:true}).waitFor();
 const received=Date.now();thermalService().ingest(devices.map(d=>({...d,lastSuccessUtc:new Date(received).toISOString()})),received,fixtureSite);
 await thermalService().siteHistory.flush();
 const stored=await thermalService().siteHistory.status();assert(stored.enabled);assert(stored.usedBytes>0);assert(stored.shardCount>=10,"Whole-site recording is independent of eight selected units");
 await storage.getByRole("button",{name:"Refresh status",exact:true}).click();
 await page.screenshot({path:path.join(directory,"thermal-storage-modal.png"),fullPage:true});
 await storage.getByRole("button",{name:"Close storage settings",exact:true}).click();
 await page.getByLabel("Recording to review",{exact:true}).selectOption("site");
 await page.getByLabel("Site history range",{exact:true}).selectOption("7");
 await page.getByRole("region",{name:"Selected thermal graphs",exact:true}).locator('.recharts-legend-item-text').first().waitFor();
 const review=page.getByLabel("History review controls",{exact:true});
 const plot=graphs.locator(".recharts-wrapper");
 await plot.click({position:{x:200,y:100}});
 const inspector=page.getByRole("region",{name:"Devices at this point",exact:true});
 await inspector.waitFor();
 const pinnedHeading=await inspector.getByRole("heading",{level:3}).innerText();
 await inspector.getByRole("button",{name:"Next device",exact:true}).click();
 const before=await inspector.getByRole("button",{pressed:true}).innerText();
 await inspector.getByRole("button",{name:"Next device",exact:true}).click();
 assert.notEqual(await inspector.getByRole("button",{pressed:true}).innerText(),before);
 assert.equal(await inspector.getByRole("heading",{level:3}).innerText(),pinnedHeading);
 await inspector.getByRole("checkbox",{name:"Show only this device",exact:true}).check();
 assert.equal(await plot.locator(".recharts-line").count(),1);
 await inspector.getByRole("button",{name:"Unpin point",exact:true}).click();
 assert(await plot.locator(".recharts-line").count()>1);

 await page.getByLabel("Graph data availability",{exact:true}).getByText(/with data/).waitFor();
 const traceLabel=graphs.getByRole("button",{name:"Array 1 · ES2 · HVAC 1",exact:true});
 await traceLabel.click();
 assert.equal(await traceLabel.getAttribute("aria-pressed"),"true");
 await graphs.getByRole("button",{name:"Clear trace highlight",exact:true}).click();
 assert.equal(await traceLabel.getAttribute("aria-pressed"),"false");

 await review.getByRole("button",{name:"Clear devices",exact:true}).click();
 await review.getByRole("checkbox",{name:"Graph device Array 1 · ES2 · HVAC 1",exact:true}).check();
 await review.getByRole("checkbox",{name:"Graph device Array 1 · ES2 · HVAC 2",exact:true}).check();
 await review.getByRole("checkbox",{name:"Graph device Array 1 · ES2 · HVAC 2",exact:true}).uncheck();
 assert((await thermalService().siteHistory.status()).enabled,"Review selection must not stop recording");
 await review.getByLabel("History minimum",{exact:true}).fill("1");
 await review.getByLabel("History maximum",{exact:true}).fill("3");
 await review.getByLabel("History operating mode",{exact:true}).selectOption("Cooling");
 await review.getByRole("button",{name:"Apply history filters",exact:true}).click();
 await page.getByText("Recorded readings · 1 shown samples",{exact:true}).click();
 const readings=page.locator("details").filter({has:page.getByText("Recorded readings · 1 shown samples",{exact:true})});
 await readings.getByRole("cell",{name:"2.0 A",exact:true}).waitFor();
 await review.getByLabel("History operating mode",{exact:true}).selectOption("Idle");
 await review.getByRole("button",{name:"Apply history filters",exact:true}).click();
 await page.getByText("No recorded observations match",{exact:true}).waitFor();
 await review.getByRole("button",{name:"Reset history filters",exact:true}).click();
 await page.getByText("Recorded readings · 1 shown samples",{exact:true}).waitFor();
 await review.getByRole("button",{name:"Add shown devices",exact:true}).click();
 assert.equal(await review.getByRole("checkbox",{checked:true}).count(),58,"Bulk selection includes the whole site");
 await review.getByRole("button",{name:"Clear devices",exact:true}).click();
 await review.getByRole("button",{name:"Select whole site",exact:true}).click();
 assert.equal(await review.getByRole("checkbox",{checked:true}).count(),58);
 await review.getByLabel("History device array",{exact:true}).selectOption("1");
 await review.getByRole("button",{name:"Select entire array",exact:true}).click();
 assert.equal(await review.getByRole("checkbox",{checked:true}).count(),8);
 await review.getByRole("button",{name:"Clear devices",exact:true}).click();
 await review.getByRole("checkbox",{name:"Graph device Array 1 · ES2 · HVAC 1",exact:true}).check();
 await review.getByLabel("History device array",{exact:true}).selectOption("2");
 await review.getByRole("button",{name:"Add shown devices",exact:true}).click();
 await review.getByRole("checkbox",{name:"Graph device Array 2 · ES5 · HVAC 1",exact:true}).uncheck();
 await review.getByRole("button",{name:"Remove shown devices",exact:true}).click();
 await review.getByLabel("History start time",{exact:true}).fill("2026-09-03T10:00");
 await review.getByLabel("History end time",{exact:true}).fill("2026-09-03T09:00");
 await review.getByRole("button",{name:"Apply history filters",exact:true}).click();
 await review.getByRole("alert").filter({hasText:"Minimum/start must not exceed"}).waitFor();
 await review.getByRole("button",{name:"Reset history filters",exact:true}).click();
 const dates=await page.evaluate(at=>{const start=new Date(at-120000),end=new Date(at+120000);return {from:new Date(start.getTime()-start.getTimezoneOffset()*60000).toISOString().slice(0,16),to:new Date(end.getTime()-end.getTimezoneOffset()*60000).toISOString().slice(0,16)};},received);
 await review.getByLabel("History start time",{exact:true}).fill(dates.from);
 await review.getByLabel("History end time",{exact:true}).fill(dates.to);
 await review.getByLabel("History minimum",{exact:true}).fill("1");
 await review.getByRole("button",{name:"Apply history filters",exact:true}).click();
 await page.getByText("Recorded readings · 1 shown samples",{exact:true}).waitFor();
 const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("button",{name:"Export shown data",exact:false}).click()]);
 const exported=JSON.parse(await fs.readFile((await download.path())!,"utf8"));
 assert.equal(exported.points.length,1);assert.equal(exported.points[0].point.current,2);assert.equal(exported.filters.minimum,1);assert(exported.points.every(p=>!p.excluded));
 await page.screenshot({path:path.join(directory,"thermal-history-review.png"),fullPage:true});
 await page.getByRole("button",{name:"Site history storage",exact:true}).click();
 await storage.getByLabel("Site retention days",{exact:true}).selectOption("1");
 await storage.getByRole("button",{name:"Save retention settings",exact:true}).click();
 await storage.getByRole("button",{name:"Stop site recording",exact:true}).waitFor({state:"visible"});
 await storage.getByRole("button",{name:"Stop site recording",exact:true}).click();
 await storage.getByText("Recording stopped",{exact:true}).waitFor();
 assert.equal((await thermalService().siteHistory.status()).retentionDays,1);
 await storage.press("Escape");
 assert.deepEqual(errors,[]);
 await page.route("**/api/local/site-data/thermal",async route=>{const {reviewVersion,...legacy}=await thermalService().view();await route.fulfill({json:legacy});});
 await page.getByRole("button",{name:"Refresh view",exact:true}).click();
 await page.getByText(/The history review update is ready/).waitFor();
 assert.equal(await page.getByLabel("History review controls",{exact:true}).count(),0,"Old servers must not show active filter controls");
 await page.unroute("**/api/local/site-data/thermal");
 await page.getByRole("button",{name:"Refresh view",exact:true}).click();
 await page.getByLabel("History review controls",{exact:true}).waitFor();
 process.env.PRIZM_THERMAL_ENABLED="false";assert.equal((await fetch(`${url}/api/local/site-data/thermal`)).status,503);
 delete process.env.PRIZM_THERMAL_ENABLED;assert.equal((await fetch(`${url}/api/local/site-data/thermal`)).status,200);
 console.log(`Thermal UI, real cached endpoints, and rollback passed. Screenshot: ${directory}/thermal-workspace.png`);
} finally {await browser.close();server.close();}
