import type { TroubleshootingEntry } from "./troubleshootingKnowledgeBase";

const stackSource = "Stack750 Troubleshooting Cheat Sheet V2 / StackOS Product Manual Rev 2";

function entry(value: TroubleshootingEntry): TroubleshootingEntry {
  return value;
}

export const DOCUMENTED_FAULT_AUGMENTATIONS: TroubleshootingEntry[] = [
  entry({
    id: "string-controller-disconnect", sourceDocument: stackSource, sourcePage: "Stack750 p.7-14; StackOS pp.112-117", section: "Notification communications", system: "string", component: "String Controller", issueName: "String Controller Disconnect", aliases: ["String Disconnect Alarm", "String Disconnect Warning", "String Disconnect Info"], faultCodes: [1025], warningCodes: [2025], infoCodes: [3025], summaryAction: "Restore communications between the BMS and affected String Controller.", recommendedActions: ["Confirm String Controller control power and status LEDs.", "Inspect the first failed network/CAN connection and both ends of the affected communications path.", "Verify the controller identity and address are unique and correctly configured.", "Perform a controlled reset only after recording active alarms and communication state."], validationChecks: ["Confirm the BMS receives current telemetry from the identified String Controller.", "Verify successive refreshes advance timestamps without timeouts."], clearingCriteria: ["The BMS hears from the String Controller and the disconnect notification clears."], detailView: "string", managerSummary: "The BMS did not hear from a String Controller before the configured timeout.", technicianDetail: "Work from the first missing controller in the chain; verify power, connector seating, addressing, and upstream communications before replacement."
  }),
  entry({
    id: "bms-disconnect", sourceDocument: stackSource, sourcePage: "Stack750 p.8-14; StackOS pp.112-117", section: "Notification communications", system: "network", component: "Network", issueName: "BMS / Phoenix Disconnect", aliases: ["BMS Disconnect Alarm", "BMS Disconnect Warning", "BMS Disconnect Info", "Phoenix Disconnect"], faultCodes: [1026], warningCodes: [2026], infoCodes: [3026], summaryAction: "Restore EMS-to-BMS communications and verify Phoenix health.", recommendedActions: ["Confirm Phoenix/BMS power, network link, and service status.", "Verify EMS and BMS addresses, subnet, and physical switch path.", "Check for duplicate IPs, stale links, or a stopped BMS service."], validationChecks: ["Ping the BMS from the EMS network.", "Confirm current BMS telemetry and heartbeat timestamps."], clearingCriteria: ["The EMS hears from the BMS and the disconnect notification clears."], detailView: "network", managerSummary: "The EMS did not hear from the BMS before timeout.", technicianDetail: "Validate the physical and logical network path before rebooting or replacing Phoenix/BMS hardware."
  }),
  entry({
    id: "pcs-disconnect", sourceDocument: stackSource, sourcePage: "Stack750 p.8-14; StackOS pp.112-117", section: "Notification communications", system: "pcs", component: "PCS", issueName: "PCS Disconnect", aliases: ["PCS Disconnect Alarm", "PCS Disconnect Warning", "PCS Disconnect Info"], faultCodes: [1027], warningCodes: [2027], infoCodes: [3027], summaryAction: "Restore EMS communications to the identified PCS.", recommendedActions: ["Confirm PCS control power and local HMI state.", "Verify PCS IP, switch port, cabling, and network route from EMS.", "Check whether the PCS is booting, faulted, or intentionally isolated."], validationChecks: ["Ping the PCS from the EMS network.", "Confirm PCS registers and timestamps update on consecutive polls."], clearingCriteria: ["EMS successfully connects to the PCS and live registers update without timeout."], detailView: "pcs", managerSummary: "EMS failed to connect to a PCS.", technicianDetail: "Use the PCS identifier and IP shown by PRIZM to verify power and the complete network path."
  }),
  entry({
    id: "meter-disconnect", sourceDocument: stackSource, sourcePage: "Stack750 p.8-14; StackOS pp.112-117", section: "Notification communications", system: "meter", component: "Meter", issueName: "Meter Disconnect", aliases: ["Meter Disconnect Alarm", "Meter Disconnect Warning", "Meter Disconnect Info"], faultCodes: [1028], warningCodes: [2028], infoCodes: [3028], summaryAction: "Restore EMS communications to the revenue or site meter.", recommendedActions: ["Confirm meter auxiliary power and display state.", "Inspect network/serial cabling, termination, address, and protocol settings.", "Verify no duplicate device address exists on the bus."], validationChecks: ["Confirm meter heartbeat and live measurements update.", "Compare PRIZM values with the local meter display."], clearingCriteria: ["EMS successfully connects to the meter and live measurements resume."], detailView: "site", managerSummary: "EMS failed to connect to the configured meter.", technicianDetail: "Verify power and communications configuration at both the meter and gateway before replacement."
  }),
  entry({
    id: "relay-heartbeat-disconnect", sourceDocument: stackSource, sourcePage: "Stack750 p.8-14; StackOS pp.112-117", section: "Notification communications", system: "network", component: "Network", issueName: "Relay Heartbeat Disconnect", aliases: ["Relay Disconnect Alarm", "Relay Disconnect Warning", "Relay Disconnect Info"], faultCodes: [1029], warningCodes: [2029], infoCodes: [3029], summaryAction: "Restore the missing protection-relay heartbeat.", recommendedActions: ["Confirm relay power and normal local status.", "Inspect the relay communications link, gateway, and configured heartbeat source.", "Verify the heartbeat timeout and device address match the deployed relay."], validationChecks: ["Observe consecutive heartbeat updates.", "Confirm relay data quality and timestamp are current."], clearingCriteria: ["EMS receives the relay heartbeat and the disconnect notification clears."], detailView: "network", managerSummary: "The expected protection-relay heartbeat was not received before timeout.", technicianDetail: "Treat the missing heartbeat as a communications fault until relay power and local status are verified."
  }),
  entry({
    id: "low-connected-string-count", sourceDocument: stackSource, sourcePage: "Stack750 p.8-14; StackOS pp.112-117", section: "Availability notifications", system: "string", component: "String Controller", issueName: "Low Connected String Count", aliases: ["Low Connected String Count Alarm", "Low Connected String Count Warning", "Low Connected String Count Info"], faultCodes: [1030], warningCodes: [2030], infoCodes: [3030], summaryAction: "Identify why the connected-string count is below the configured minimum.", recommendedActions: ["Review out-of-rotation, open-contactor, and non-communicating strings by array.", "Resolve common upstream interlocks before working individual strings.", "Verify the configured minimum connected-string threshold is appropriate for the operating mode."], validationChecks: ["Confirm each recovered string communicates and has valid contactor state.", "Compare connected count with the configured threshold."], clearingCriteria: ["A sufficient number of strings are connected and the count notification clears."], detailView: "string", managerSummary: "Too few strings are connected for the configured operating threshold.", technicianDetail: "Use grouped corrective actions to separate common-cause outages from isolated string faults."
  }),
  entry({
    id: "abnormal-string-current", sourceDocument: stackSource, sourcePage: "Stack750 p.8-14; StackOS pp.112-117", section: "Current notifications", system: "string", component: "String Controller", issueName: "Abnormal String Current", aliases: ["Abnormal String Current Alarm", "Abnormal String Current Warning", "Abnormal String Current Info"], faultCodes: [1046], warningCodes: [2046], infoCodes: [3046], summaryAction: "Verify unexpected string current while the PCS is off.", recommendedActions: ["Confirm PCS operating state and commanded power are actually zero.", "Compare the affected string current with adjacent strings and the second current sensor when available.", "Inspect contactor feedback, current-sensor zero, polarity, and mapping."], validationChecks: ["Measure string current independently when safe.", "Confirm sensor zero and contactor state agree with physical conditions."], clearingCriteria: ["String current falls below the configured setting or the PCS returns to an operating state consistent with measured current."], detailView: "string", managerSummary: "Current is reported on a string while the PCS is off and expected current is zero.", technicianDetail: "Rule out stale PCS state and current-sensor offset/mapping before opening the power circuit."
  }),
  entry({
    id: "string-current-delta", sourceDocument: stackSource, sourcePage: "Stack750 p.8-14; StackOS pp.112-117", section: "Current notifications", system: "string", component: "String Controller", issueName: "String Current Delta", aliases: ["String Current Delta Alarm", "String Current Delta Warning", "String Current Delta Info"], faultCodes: [1047], warningCodes: [2047], infoCodes: [3047], summaryAction: "Investigate why the selected string current differs from the fleet average.", recommendedActions: ["Compare SOC, voltage, contactor state, and current across peer strings in the same array.", "Validate current-sensor zero, polarity, and scaling on the affected string.", "Check for resistance, fuse, contactor, or connection problems causing unequal current."], validationChecks: ["Compare independent current measurement with telemetry.", "Confirm the current difference remains below the configured threshold during a stable operating interval."], clearingCriteria: ["The affected string current difference falls below the configured delta threshold; alarm variants may require manual clearing."], detailView: "string", managerSummary: "A string current differs from the average by more than the configured percentage.", technicianDetail: "Compare like-for-like strings under stable PCS power before concluding the sensor or power path is faulty."
  }),
  entry({
    id: "controller-internal-error", sourceDocument: stackSource, sourcePage: "Stack750 p.8, 11, 14; StackOS pp.113, 116", section: "Internal error notifications", system: "network", component: "Unknown", issueName: "Controller Internal Error", aliases: ["CGC Internal Error Alarm", "BPC Internal Error Alarm", "SC Internal Error Alarm", "BMS/Phoenix Internal Error Alarm", "EMS/Dragon Internal Error Alarm", "CGC Internal Error Warning", "BPC Internal Error Warning", "SC Internal Error Warning", "BMS/Phoenix Internal Error Warning", "EMS/Dragon Internal Error Warning", "CGC Internal Error Info", "BPC Internal Error Info", "SC Internal Error Info", "BMS/Phoenix Internal Error Info", "EMS/Dragon Internal Error Info"], faultCodes: [1048,1049,1050,1051,1052], warningCodes: [2048,2049,2050,2051,2052], infoCodes: [3048,3049,3050,3051,3052], summaryAction: "Capture the native trigger message and inspect the identified controller before reset.", recommendedActions: ["Record the exact controller, severity, native trigger, and timestamp.", "Verify controller power, communications, firmware state, and nearby related faults.", "For SC trigger message 5, compare both DC bus current sensors for mismatch.", "Perform a controlled reset only after evidence is captured and site safety conditions permit."], validationChecks: ["Confirm the native internal-error register is no longer asserted.", "Verify telemetry remains stable through consecutive refreshes."], clearingCriteria: ["The controller no longer reports the internal error; alarm-severity variants may require authorized manual clearing."], detailView: "site", managerSummary: "A CGC, BPC, SC, BMS/Phoenix, or EMS/Dragon controller reported an internal error.", technicianDetail: "Preserve the native trigger before reset because it identifies the underlying controller condition."
  }),
  entry({
    id: "string-fuse-open", sourceDocument: "POM-013 Centipede Troubleshooting Guide Rev 1 / Stack750 Troubleshooting Cheat Sheet V2", sourcePage: "POM-013 pp.34-35; Stack750 p.9", section: "String Controller power path", system: "string", component: "String Controller", issueName: "String Fuse Open", aliases: ["String Fuse Open Alarm"], faultCodes: [1559], summaryAction: "De-energize under the approved procedure, identify the open fuse, and determine its cause before replacement.", recommendedActions: ["Follow the site energy-control plan and verify absence of hazardous voltage before continuity testing.", "Check the applicable SC AC and DC fuses for continuity.", "Inspect wiring and downstream loads for damage or a short before replacing an open fuse.", "Replace only with the approved fuse type and rating."], validationChecks: ["Verify replacement fuse continuity and correct installation.", "Confirm normal SC power outputs and no recurring overcurrent condition."], clearingCriteria: ["The fuse-open condition is corrected, SC power is restored, and the alarm is manually cleared by an authorized operator."], detailView: "string", managerSummary: "The String Controller reports an opened fuse; root cause must be checked before replacement.", technicianDetail: "POM-013 shows AC/DC fuse continuity checks and SC fuse locations. Do not probe energized circuits outside the approved work plan.", safetyNote: "Hazardous voltage: apply the Centipede Energy Control Plan and required PPE before opening or testing String Controller circuits."
  }),
  entry({
    id: "contactor-open-notification", sourceDocument: "POM-013 Centipede Troubleshooting Guide Rev 1 / StackOS Product Manual Rev 2", sourcePage: "POM-013 pp.34-36; StackOS pp.114, 117", section: "String Controller contactors", system: "contactor", component: "Contactor", issueName: "Contactor Open / Error", aliases: ["Contactor Open Warning", "Contactor Error"], warningCodes: [2534], infoCodes: [3536], summaryAction: "Compare commanded and physical contactor states, then inspect feedback wiring and the contactor mechanism.", recommendedActions: ["Verify whether each contactor is physically open or closed before tracing feedback.", "Inspect loose crimps or severed black/white auxiliary-feedback wiring.", "Check for dirt or sand ingress at the external contactor switch and joined ground-side wiring.", "Replace a mechanically or internally damaged contactor under the approved maintenance procedure."], validationChecks: ["Measure auxiliary-contact continuity in both physical states.", "Confirm both contactors follow commands and feedback agrees with physical position."], clearingCriteria: ["Both contactors close when commanded and the reported contactor state matches physical state."], detailView: "string", managerSummary: "The SC detected an open contactor or contactor feedback error.", technicianDetail: "POM-013 identifies severed wires, loose crimps, contamination, and internal contactor damage as leading causes."
  }),
  entry({
    id: "device-booter-mode", sourceDocument: stackSource, sourcePage: "Stack750 p.15; StackOS pp.117-118", section: "Firmware state notifications", system: "network", component: "Unknown", issueName: "Device Stuck in Booter Mode", aliases: ["BPC Booter Mode", "CGC Booter Mode", "String Controller Booter Mode", "Phoenix Booter Mode", "Dragon Booter Mode"], infoCodes: [3537,3538,3539,3540,3541], summaryAction: "Identify why the controller did not leave bootloader mode and restore its application firmware safely.", recommendedActions: ["Record the affected device, firmware version, and update history.", "Verify stable control power and communications to the device.", "Retry the approved firmware/update workflow only with the correct image and recovery procedure.", "Escalate repeated bootloader returns before replacing hardware."], validationChecks: ["Confirm the device boots into its normal application.", "Verify normal telemetry and firmware version after recovery."], clearingCriteria: ["The notification clears when the affected controller leaves Booter Mode and resumes normal communication."], detailView: "site", managerSummary: "A BPC, CGC, String Controller, Phoenix, or Dragon controller remains in bootloader mode.", technicianDetail: "Do not interrupt power during an authorized recovery flash; verify the exact target and firmware image first."
  })
];
